-- ============================================================================
-- Consolidated schema for Supabase project qsrlfsjtuymuhvwnsegq
-- Auto-generated by concatenating supabase/migrations/*.sql in order.
-- Paste this whole file into the Supabase SQL Editor and Run, OR use the CLI
--   (supabase link --project-ref qsrlfsjtuymuhvwnsegq && supabase db push).
-- Safe to delete this file afterwards; migrations/ remains the source of truth.
-- ============================================================================


-- ===== 20260128034023_365d201c-85e9-4999-9a6f-82e90d798a2b.sql ============================================
-- Create app_role enum for admin roles
CREATE TYPE public.app_role AS ENUM ('admin');

-- Create user_roles table for storing admin roles
CREATE TABLE public.user_roles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    role app_role NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UNIQUE (user_id, role)
);

-- Enable RLS on user_roles
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Create security definer function to check admin role
CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role app_role)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles
    WHERE user_id = _user_id
      AND role = _role
  )
$$;

-- Create helper function to check if current user is admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.has_role(auth.uid(), 'admin')
$$;

-- RLS policies for user_roles table
CREATE POLICY "Admins can view all roles"
ON public.user_roles
FOR SELECT
TO authenticated
USING (public.is_admin());

-- Create appointments table
CREATE TABLE public.appointments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    customer_phone TEXT,
    company TEXT,
    appointment_date DATE NOT NULL,
    appointment_time TIME NOT NULL,
    service_type TEXT NOT NULL,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'cancelled', 'completed', 'postponed', 'declined')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS on appointments
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

-- Anyone can create appointments (public booking form)
CREATE POLICY "Anyone can create appointments"
ON public.appointments
FOR INSERT
WITH CHECK (true);

-- Only admins can view all appointments
CREATE POLICY "Admins can view all appointments"
ON public.appointments
FOR SELECT
TO authenticated
USING (public.is_admin());

-- Only admins can update appointments
CREATE POLICY "Admins can update appointments"
ON public.appointments
FOR UPDATE
TO authenticated
USING (public.is_admin());

-- Only admins can delete appointments
CREATE POLICY "Admins can delete appointments"
ON public.appointments
FOR DELETE
TO authenticated
USING (public.is_admin());

-- Create enquiries table
CREATE TABLE public.enquiries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    company TEXT,
    subject TEXT,
    message TEXT NOT NULL,
    enquiry_type TEXT NOT NULL DEFAULT 'general' CHECK (enquiry_type IN ('general', 'quote', 'product', 'support')),
    product_id TEXT,
    product_name TEXT,
    status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'read', 'responded', 'closed')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS on enquiries
ALTER TABLE public.enquiries ENABLE ROW LEVEL SECURITY;

-- Anyone can create enquiries (public contact form)
CREATE POLICY "Anyone can create enquiries"
ON public.enquiries
FOR INSERT
WITH CHECK (true);

-- Only admins can view all enquiries
CREATE POLICY "Admins can view all enquiries"
ON public.enquiries
FOR SELECT
TO authenticated
USING (public.is_admin());

-- Only admins can update enquiries
CREATE POLICY "Admins can update enquiries"
ON public.enquiries
FOR UPDATE
TO authenticated
USING (public.is_admin());

-- Only admins can delete enquiries
CREATE POLICY "Admins can delete enquiries"
ON public.enquiries
FOR DELETE
TO authenticated
USING (public.is_admin());

-- Create updated_at trigger function
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

-- Create triggers for updated_at
CREATE TRIGGER update_appointments_updated_at
BEFORE UPDATE ON public.appointments
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_enquiries_updated_at
BEFORE UPDATE ON public.enquiries
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- ===== 20260128105516_05bc29e7-1d91-4d26-b4fe-c741d2921356.sql ============================================
-- Create table to store booking OTPs
CREATE TABLE public.booking_otps (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT NOT NULL,
    otp_hash TEXT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    verified BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.booking_otps ENABLE ROW LEVEL SECURITY;

-- Anyone can create OTPs (for booking verification)
CREATE POLICY "Anyone can create booking OTPs"
ON public.booking_otps
FOR INSERT
WITH CHECK (true);

-- Anyone can read their own OTPs by email (for verification)
CREATE POLICY "Anyone can verify OTPs"
ON public.booking_otps
FOR SELECT
USING (true);

-- Anyone can update OTPs (to mark as verified)
CREATE POLICY "Anyone can update OTPs"
ON public.booking_otps
FOR UPDATE
USING (true);

-- Clean up old OTPs automatically (delete expired ones)
CREATE POLICY "Anyone can delete expired OTPs"
ON public.booking_otps
FOR DELETE
USING (expires_at < now());

-- Create index for faster lookups
CREATE INDEX idx_booking_otps_email ON public.booking_otps(email);
CREATE INDEX idx_booking_otps_expires_at ON public.booking_otps(expires_at);

-- ===== 20260128164458_a61b4144-a9fc-40e3-84ab-ee9589c3a6e2.sql ============================================
-- Fix booking_otps RLS policies: Remove public SELECT/UPDATE access
-- Only edge functions with service role should be able to read/update OTPs

-- Drop existing vulnerable policies
DROP POLICY IF EXISTS "Anyone can verify OTPs" ON public.booking_otps;
DROP POLICY IF EXISTS "Anyone can update OTPs" ON public.booking_otps;
DROP POLICY IF EXISTS "Anyone can delete expired OTPs" ON public.booking_otps;
DROP POLICY IF EXISTS "Anyone can create booking OTPs" ON public.booking_otps;

-- Create new secure policies:
-- Only allow INSERT from edge functions (public can still insert via edge function that uses service role)
-- SELECT, UPDATE, DELETE should only be possible via service role (edge functions)
-- We keep RLS enabled but remove all public access policies for SELECT/UPDATE/DELETE

-- Allow public INSERT only (the send-booking-otp edge function inserts with service role anyway)
CREATE POLICY "Service role can manage OTPs" 
ON public.booking_otps 
FOR ALL 
USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');

-- ===== 20260129163214_9ad63b4d-8800-4d5a-89f5-2b542f8a0189.sql ============================================
-- Fix overly permissive RLS policies by explicitly specifying the anon role
-- This makes the intentional public access clear to the linter

-- Drop existing permissive INSERT policies
DROP POLICY IF EXISTS "Anyone can create appointments" ON public.appointments;
DROP POLICY IF EXISTS "Anyone can create enquiries" ON public.enquiries;

-- Recreate INSERT policies with explicit role specification
-- For appointments: Allow anonymous users to create appointments (public booking form)
CREATE POLICY "Public can create appointments"
ON public.appointments
FOR INSERT
TO anon
WITH CHECK (true);

-- For enquiries: Allow anonymous users to create enquiries (public contact form)
CREATE POLICY "Public can create enquiries"
ON public.enquiries
FOR INSERT
TO anon
WITH CHECK (true);

-- ===== 20260129173750_c8face05-c06c-4cf6-bb68-b82d50af6c5a.sql ============================================
-- First, let's create a products table for live product management
CREATE TABLE public.products (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  short_description TEXT,
  description TEXT,
  category TEXT NOT NULL,
  category_slug TEXT NOT NULL,
  price DECIMAL(10,2),
  image_url TEXT,
  features TEXT[] DEFAULT '{}',
  specifications JSONB DEFAULT '{}',
  in_stock BOOLEAN DEFAULT true,
  is_featured BOOLEAN DEFAULT false,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS on products table
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Public can view all products
CREATE POLICY "Anyone can view products"
ON public.products
FOR SELECT
TO anon, authenticated
USING (true);

-- Only admins can insert products
CREATE POLICY "Admins can insert products"
ON public.products
FOR INSERT
TO authenticated
WITH CHECK (is_admin());

-- Only admins can update products
CREATE POLICY "Admins can update products"
ON public.products
FOR UPDATE
TO authenticated
USING (is_admin());

-- Only admins can delete products
CREATE POLICY "Admins can delete products"
ON public.products
FOR DELETE
TO authenticated
USING (is_admin());

-- Create categories table for live category management
CREATE TABLE public.categories (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  image_url TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS on categories table
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- Public can view all categories
CREATE POLICY "Anyone can view categories"
ON public.categories
FOR SELECT
TO anon, authenticated
USING (true);

-- Only admins can manage categories
CREATE POLICY "Admins can insert categories"
ON public.categories
FOR INSERT
TO authenticated
WITH CHECK (is_admin());

CREATE POLICY "Admins can update categories"
ON public.categories
FOR UPDATE
TO authenticated
USING (is_admin());

CREATE POLICY "Admins can delete categories"
ON public.categories
FOR DELETE
TO authenticated
USING (is_admin());

-- Add triggers for updated_at timestamps
CREATE TRIGGER update_products_updated_at
BEFORE UPDATE ON public.products
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_categories_updated_at
BEFORE UPDATE ON public.categories
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Enable realtime for appointments, products, and categories
ALTER PUBLICATION supabase_realtime ADD TABLE public.appointments;
ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
ALTER PUBLICATION supabase_realtime ADD TABLE public.categories;

-- Seed initial categories
INSERT INTO public.categories (name, slug, description, sort_order) VALUES
('Portable Cabins', 'portable-cabins', 'Modular portable cabin solutions', 1),
('Container Offices', 'container-offices', 'Converted shipping container offices', 2),
('Security Cabins', 'security-cabins', 'Guard houses and security checkpoints', 3),
('Portable Toilets', 'portable-toilets', 'Mobile sanitation solutions', 4),
('Prefab Homes', 'prefab-homes', 'Prefabricated residential structures', 5),
('Site Offices', 'site-offices', 'Temporary on-site office solutions', 6);

-- ===== 20260130135405_3116d077-1f58-4d40-aa45-873bd8093083.sql ============================================
-- Create table for page views tracking
CREATE TABLE public.page_views (
    id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    visitor_id TEXT NOT NULL,
    page_path TEXT NOT NULL,
    page_title TEXT,
    referrer TEXT,
    user_agent TEXT,
    duration_seconds INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create table for click/keyword tracking
CREATE TABLE public.click_events (
    id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    visitor_id TEXT NOT NULL,
    page_path TEXT NOT NULL,
    element_type TEXT NOT NULL,
    element_text TEXT,
    element_id TEXT,
    element_class TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create indexes for better query performance
CREATE INDEX idx_page_views_created_at ON public.page_views(created_at DESC);
CREATE INDEX idx_page_views_page_path ON public.page_views(page_path);
CREATE INDEX idx_page_views_visitor_id ON public.page_views(visitor_id);
CREATE INDEX idx_click_events_created_at ON public.click_events(created_at DESC);
CREATE INDEX idx_click_events_element_text ON public.click_events(element_text);

-- Enable RLS
ALTER TABLE public.page_views ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.click_events ENABLE ROW LEVEL SECURITY;

-- Allow public inserts for tracking (anonymous visitors)
CREATE POLICY "Anyone can insert page views"
ON public.page_views
FOR INSERT
TO anon
WITH CHECK (true);

CREATE POLICY "Anyone can insert click events"
ON public.click_events
FOR INSERT
TO anon
WITH CHECK (true);

-- Allow admins to view all analytics
CREATE POLICY "Admins can view page views"
ON public.page_views
FOR SELECT
USING (public.is_admin());

CREATE POLICY "Admins can view click events"
ON public.click_events
FOR SELECT
USING (public.is_admin());

-- Allow admins to delete old analytics data
CREATE POLICY "Admins can delete page views"
ON public.page_views
FOR DELETE
USING (public.is_admin());

CREATE POLICY "Admins can delete click events"
ON public.click_events
FOR DELETE
USING (public.is_admin());

-- ===== 20260130141117_19d0e87d-7623-458b-87d5-6b1e6936b1d5.sql ============================================
-- Drop the restrictive INSERT policies and recreate as permissive

-- Fix enquiries table
DROP POLICY IF EXISTS "Public can create enquiries" ON public.enquiries;
CREATE POLICY "Public can create enquiries" 
ON public.enquiries 
FOR INSERT 
TO anon, authenticated
WITH CHECK (true);

-- Fix appointments table
DROP POLICY IF EXISTS "Public can create appointments" ON public.appointments;
CREATE POLICY "Public can create appointments" 
ON public.appointments 
FOR INSERT 
TO anon, authenticated
WITH CHECK (true);

-- Fix page_views table
DROP POLICY IF EXISTS "Anyone can insert page views" ON public.page_views;
CREATE POLICY "Anyone can insert page views" 
ON public.page_views 
FOR INSERT 
TO anon, authenticated
WITH CHECK (true);

-- Fix click_events table
DROP POLICY IF EXISTS "Anyone can insert click events" ON public.click_events;
CREATE POLICY "Anyone can insert click events" 
ON public.click_events 
FOR INSERT 
TO anon, authenticated
WITH CHECK (true);

-- ===== 20260203111357_6c69507d-5fcc-4cef-a2de-d146f32334c6.sql ============================================
-- Add unique constraint to prevent multiple admin accounts (prevents race condition)
-- This creates a partial unique index that only allows one row with role = 'admin'
CREATE UNIQUE INDEX IF NOT EXISTS idx_single_admin 
ON public.user_roles (role) 
WHERE role = 'admin';

-- ===== 20260214160903_535aab18-8257-4fcb-b9b0-eb852a749f02.sql ============================================

-- Profiles table for user accounts
CREATE TABLE public.profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text,
  phone text,
  company text,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  pincode text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Admins can view all profiles" ON public.profiles FOR SELECT USING (public.is_admin());

-- Auto-create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (user_id, full_name)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'full_name', ''));
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- Cart items table
CREATE TABLE public.cart_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  customization_notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(user_id, product_id)
);

ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own cart" ON public.cart_items FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Order status enum
CREATE TYPE public.order_status AS ENUM (
  'pending', 'confirmed', 'manufacturing', 'quality_check', 'dispatched', 'in_transit', 'delivered', 'cancelled'
);

-- Orders table
CREATE TABLE public.orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number text NOT NULL UNIQUE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status order_status NOT NULL DEFAULT 'pending',
  total_amount numeric,
  payment_method text DEFAULT 'quote_request',
  payment_status text DEFAULT 'pending',
  shipping_address_line1 text,
  shipping_address_line2 text,
  shipping_city text,
  shipping_state text,
  shipping_pincode text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own orders" ON public.orders FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create orders" ON public.orders FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins can manage all orders" ON public.orders FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- Order items table
CREATE TABLE public.order_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id uuid,
  product_name text NOT NULL,
  product_sku text,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric,
  customization_notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own order items" ON public.order_items FOR SELECT 
  USING (EXISTS (SELECT 1 FROM public.orders WHERE orders.id = order_items.order_id AND orders.user_id = auth.uid()));
CREATE POLICY "Users can insert order items" ON public.order_items FOR INSERT 
  WITH CHECK (EXISTS (SELECT 1 FROM public.orders WHERE orders.id = order_items.order_id AND orders.user_id = auth.uid()));
CREATE POLICY "Admins can manage order items" ON public.order_items FOR ALL 
  USING (public.is_admin()) WITH CHECK (public.is_admin());

-- Order status history for tracking
CREATE TABLE public.order_status_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  status order_status NOT NULL,
  notes text,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.order_status_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own order history" ON public.order_status_history FOR SELECT 
  USING (EXISTS (SELECT 1 FROM public.orders WHERE orders.id = order_status_history.order_id AND orders.user_id = auth.uid()));
CREATE POLICY "Admins can manage order history" ON public.order_status_history FOR ALL 
  USING (public.is_admin()) WITH CHECK (public.is_admin());

-- Function to generate order number
CREATE OR REPLACE FUNCTION public.generate_order_number()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  seq_num integer;
BEGIN
  SELECT COALESCE(MAX(CAST(SUBSTRING(order_number FROM 'ORD-(\d+)') AS integer)), 10000) + 1
  INTO seq_num
  FROM public.orders;
  
  NEW.order_number := 'ORD-' || seq_num;
  RETURN NEW;
END;
$$;

CREATE TRIGGER set_order_number
  BEFORE INSERT ON public.orders
  FOR EACH ROW
  WHEN (NEW.order_number IS NULL OR NEW.order_number = '')
  EXECUTE FUNCTION public.generate_order_number();

-- Update triggers
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_cart_items_updated_at BEFORE UPDATE ON public.cart_items FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Enable realtime for orders
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
ALTER PUBLICATION supabase_realtime ADD TABLE public.order_status_history;


-- ===== 20260214161611_10f84aae-991f-422b-88e2-bcb539379d14.sql ============================================

-- Drop the foreign key and change product_id to text to support local product IDs
ALTER TABLE public.cart_items DROP CONSTRAINT cart_items_product_id_fkey;
ALTER TABLE public.cart_items ALTER COLUMN product_id TYPE text USING product_id::text;

-- Also fix order_items product_id to text
ALTER TABLE public.order_items ALTER COLUMN product_id TYPE text USING product_id::text;


-- ===== 20260429171552_446fe923-538c-4d2f-8f62-4ccb8c8afdfe.sql ============================================
-- Add 'staff' to app_role enum if not present
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'staff' AND enumtypid = 'public.app_role'::regtype) THEN
    ALTER TYPE public.app_role ADD VALUE 'staff';
  END IF;
END $$;

-- Extend enquiries
ALTER TABLE public.enquiries
  ADD COLUMN IF NOT EXISTS pipeline_stage text NOT NULL DEFAULT 'new',
  ADD COLUMN IF NOT EXISTS assigned_to uuid,
  ADD COLUMN IF NOT EXISTS expected_value numeric,
  ADD COLUMN IF NOT EXISTS next_followup_at timestamptz,
  ADD COLUMN IF NOT EXISTS lost_reason text;

-- Extend appointments
ALTER TABLE public.appointments
  ADD COLUMN IF NOT EXISTS pipeline_stage text NOT NULL DEFAULT 'new',
  ADD COLUMN IF NOT EXISTS assigned_to uuid,
  ADD COLUMN IF NOT EXISTS next_followup_at timestamptz;

-- Extend products (inventory)
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS stock_quantity integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS low_stock_threshold integer NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS sku text,
  ADD COLUMN IF NOT EXISTS supplier_id uuid;

-- Extend orders (invoicing)
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS invoice_number text,
  ADD COLUMN IF NOT EXISTS invoice_generated_at timestamptz,
  ADD COLUMN IF NOT EXISTS paid_amount numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS due_amount numeric NOT NULL DEFAULT 0;

-- Customer notes
CREATE TABLE IF NOT EXISTS public.customer_notes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  note text NOT NULL,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.customer_notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage customer notes" ON public.customer_notes
  FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- Customer tags
CREATE TABLE IF NOT EXISTS public.customer_tags (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  tag text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(user_id, tag)
);
ALTER TABLE public.customer_tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage customer tags" ON public.customer_tags
  FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- Lead activities (follow-ups)
CREATE TABLE IF NOT EXISTS public.lead_activities (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  enquiry_id uuid,
  appointment_id uuid,
  activity_type text NOT NULL DEFAULT 'note',
  content text NOT NULL,
  scheduled_at timestamptz,
  completed boolean NOT NULL DEFAULT false,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.lead_activities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage lead activities" ON public.lead_activities
  FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- Suppliers
CREATE TABLE IF NOT EXISTS public.suppliers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  contact_person text,
  email text,
  phone text,
  address text,
  gst_number text,
  lead_time_days integer DEFAULT 7,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage suppliers" ON public.suppliers
  FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE TRIGGER trg_suppliers_updated BEFORE UPDATE ON public.suppliers
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Inventory movements
CREATE TABLE IF NOT EXISTS public.inventory_movements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id text NOT NULL,
  movement_type text NOT NULL,
  quantity integer NOT NULL,
  reason text,
  reference text,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.inventory_movements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage inventory movements" ON public.inventory_movements
  FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- Site settings (key/value)
CREATE TABLE IF NOT EXISTS public.site_settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  value jsonb NOT NULL DEFAULT '{}'::jsonb,
  description text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid
);
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage site settings" ON public.site_settings
  FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE TRIGGER trg_site_settings_updated BEFORE UPDATE ON public.site_settings
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ===== 20260429174113_a84081f6-12ad-4bf6-87fe-eecfc0d162ce.sql ============================================
ALTER TABLE public.page_views
  ADD COLUMN IF NOT EXISTS ip_address text,
  ADD COLUMN IF NOT EXISTS country text,
  ADD COLUMN IF NOT EXISTS region text,
  ADD COLUMN IF NOT EXISTS city text;

CREATE INDEX IF NOT EXISTS idx_page_views_visitor_id ON public.page_views(visitor_id);
CREATE INDEX IF NOT EXISTS idx_page_views_created_at ON public.page_views(created_at DESC);

-- ===== 20260430025927_5192b1b0-d722-4ad8-9dac-543d77a77899.sql ============================================
CREATE TABLE public.spec_documents (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  client_name TEXT,
  project_details TEXT,
  doc_date DATE,
  ref_number TEXT,
  sections JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_by UUID,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.spec_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage spec documents"
ON public.spec_documents
FOR ALL
TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());

CREATE TRIGGER update_spec_documents_updated_at
BEFORE UPDATE ON public.spec_documents
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

CREATE INDEX idx_spec_documents_created_at ON public.spec_documents (created_at DESC);

-- ===== 20260430145316_ef8caab4-646f-43e6-89de-a05baae28a30.sql ============================================

-- Quotations table
CREATE TABLE public.quotations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  quotation_number text NOT NULL DEFAULT '',
  client_name text NOT NULL,
  client_email text,
  client_phone text,
  client_company text,
  client_address text,
  subject text,
  notes text,
  terms text DEFAULT 'Prices are exclusive of GST, transportation, and installation charges.',
  validity_days integer DEFAULT 15,
  subtotal numeric DEFAULT 0,
  gst_percent numeric DEFAULT 18,
  gst_amount numeric DEFAULT 0,
  total_amount numeric DEFAULT 0,
  status text NOT NULL DEFAULT 'draft',
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.quotations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage quotations" ON public.quotations FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

CREATE TRIGGER update_quotations_updated_at BEFORE UPDATE ON public.quotations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Auto-generate quotation number
CREATE OR REPLACE FUNCTION public.generate_quotation_number()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
DECLARE seq_num integer;
BEGIN
  SELECT COALESCE(MAX(CAST(SUBSTRING(quotation_number FROM 'QTN-(\d+)') AS integer)), 1000) + 1 INTO seq_num FROM public.quotations;
  NEW.quotation_number := 'QTN-' || seq_num;
  RETURN NEW;
END;
$$;

CREATE TRIGGER set_quotation_number BEFORE INSERT ON public.quotations FOR EACH ROW EXECUTE FUNCTION generate_quotation_number();

-- Quotation items
CREATE TABLE public.quotation_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  quotation_id uuid NOT NULL REFERENCES public.quotations(id) ON DELETE CASCADE,
  description text NOT NULL,
  unit text DEFAULT 'Nos',
  quantity numeric NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL DEFAULT 0,
  total_price numeric NOT NULL DEFAULT 0,
  sort_order integer DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.quotation_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage quotation items" ON public.quotation_items FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- Sales Orders table
CREATE TABLE public.sales_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  so_number text NOT NULL DEFAULT '',
  quotation_id uuid REFERENCES public.quotations(id),
  client_name text NOT NULL,
  client_email text,
  client_phone text,
  client_company text,
  client_address text,
  delivery_date date,
  subtotal numeric DEFAULT 0,
  gst_percent numeric DEFAULT 18,
  gst_amount numeric DEFAULT 0,
  total_amount numeric DEFAULT 0,
  status text NOT NULL DEFAULT 'pending',
  payment_status text NOT NULL DEFAULT 'pending',
  notes text,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.sales_orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage sales orders" ON public.sales_orders FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

CREATE TRIGGER update_sales_orders_updated_at BEFORE UPDATE ON public.sales_orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Auto-generate SO number
CREATE OR REPLACE FUNCTION public.generate_so_number()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
DECLARE seq_num integer;
BEGIN
  SELECT COALESCE(MAX(CAST(SUBSTRING(so_number FROM 'SO-(\d+)') AS integer)), 5000) + 1 INTO seq_num FROM public.sales_orders;
  NEW.so_number := 'SO-' || seq_num;
  RETURN NEW;
END;
$$;

CREATE TRIGGER set_so_number BEFORE INSERT ON public.sales_orders FOR EACH ROW EXECUTE FUNCTION generate_so_number();

-- Sales Order items
CREATE TABLE public.sales_order_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sales_order_id uuid NOT NULL REFERENCES public.sales_orders(id) ON DELETE CASCADE,
  description text NOT NULL,
  unit text DEFAULT 'Nos',
  quantity numeric NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL DEFAULT 0,
  total_price numeric NOT NULL DEFAULT 0,
  sort_order integer DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.sales_order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage sales order items" ON public.sales_order_items FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());


-- ===== 20260430152331_ad5f01d7-7756-47ba-b18d-5606ca7d9a5b.sql ============================================

-- Add CRM columns to enquiries
ALTER TABLE public.enquiries
  ADD COLUMN IF NOT EXISTS lead_source text NOT NULL DEFAULT 'website',
  ADD COLUMN IF NOT EXISTS lead_status text NOT NULL DEFAULT 'new';

-- Follow-ups table
CREATE TABLE public.follow_ups (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  enquiry_id uuid NOT NULL,
  follow_up_type text NOT NULL DEFAULT 'call',
  notes text,
  scheduled_at timestamp with time zone,
  completed boolean NOT NULL DEFAULT false,
  completed_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.follow_ups ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage follow ups"
  ON public.follow_ups FOR ALL
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

CREATE INDEX idx_follow_ups_enquiry ON public.follow_ups(enquiry_id);
CREATE INDEX idx_follow_ups_scheduled ON public.follow_ups(scheduled_at);
CREATE INDEX idx_enquiries_lead_status ON public.enquiries(lead_status);
CREATE INDEX idx_enquiries_lead_source ON public.enquiries(lead_source);


-- ===== 20260430160715_049e09f5-9ef0-4865-a878-9a383bcba4ad.sql ============================================

-- Create a sequence starting after the current max
DO $$
DECLARE max_num integer;
BEGIN
  SELECT COALESCE(MAX(CAST(SUBSTRING(order_number FROM 'ORD-(\d+)') AS integer)), 10000)
  INTO max_num FROM public.orders;
  EXECUTE format('CREATE SEQUENCE IF NOT EXISTS public.order_number_seq START WITH %s', max_num + 1);
END $$;

-- Replace the trigger function to use the sequence
CREATE OR REPLACE FUNCTION public.generate_order_number()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  NEW.order_number := 'ORD-' || nextval('public.order_number_seq');
  RETURN NEW;
END;
$function$;


-- ===== 20260430161946_a3db38f9-71e1-4afb-aadf-c6e4802fe8b9.sql ============================================

-- Tasks table for team task management
CREATE TABLE public.tasks (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  assigned_to TEXT,
  due_date DATE,
  priority TEXT NOT NULL DEFAULT 'medium',
  status TEXT NOT NULL DEFAULT 'pending',
  related_enquiry_id UUID,
  created_by UUID,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage tasks" ON public.tasks FOR ALL TO authenticated
  USING (is_admin()) WITH CHECK (is_admin());

CREATE TRIGGER update_tasks_updated_at BEFORE UPDATE ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Service requests table
CREATE TABLE public.service_requests (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_email TEXT,
  customer_phone TEXT,
  request_type TEXT NOT NULL DEFAULT 'service',
  subject TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'open',
  priority TEXT NOT NULL DEFAULT 'medium',
  resolution_notes TEXT,
  resolved_at TIMESTAMP WITH TIME ZONE,
  created_by UUID,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.service_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage service requests" ON public.service_requests FOR ALL TO authenticated
  USING (is_admin()) WITH CHECK (is_admin());

CREATE POLICY "Public can create service requests" ON public.service_requests FOR INSERT TO anon
  WITH CHECK (true);

CREATE TRIGGER update_service_requests_updated_at BEFORE UPDATE ON public.service_requests
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


-- ===== 20260506022313_b3aa609f-e2fe-4fa4-8856-372ecbaded1d.sql ============================================

-- ============================================================
-- INVENTORY & MATERIAL TRACKING MODULE - FULL SCHEMA
-- ============================================================

-- 1. FACTORIES
CREATE TABLE public.factories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  code text NOT NULL UNIQUE,
  location text NOT NULL,
  state text,
  address text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.factories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage factories" ON public.factories FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE TRIGGER trg_factories_updated_at BEFORE UPDATE ON public.factories FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

INSERT INTO public.factories (name, code, location, state, address) VALUES
  ('Bangalore Factory', 'BLR', 'Bangalore', 'Karnataka', 'Bangalore, Karnataka'),
  ('Hosur Factory', 'HSR', 'Hosur', 'Tamil Nadu', 'Hosur, Tamil Nadu');

-- 2. MATERIALS (Master)
CREATE TABLE public.materials (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  category text NOT NULL,
  size text,
  thickness text,
  brand text,
  unit text NOT NULL DEFAULT 'Nos',
  opening_stock numeric NOT NULL DEFAULT 0,
  min_stock_alert numeric NOT NULL DEFAULT 0,
  purchase_rate numeric NOT NULL DEFAULT 0,
  supplier_id uuid REFERENCES public.suppliers(id) ON DELETE SET NULL,
  hsn_code text,
  gst_percent numeric NOT NULL DEFAULT 18,
  sku text,
  barcode text,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage materials" ON public.materials FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE TRIGGER trg_materials_updated_at BEFORE UPDATE ON public.materials FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE INDEX idx_materials_category ON public.materials(category);

-- 3. MATERIAL STOCK PER FACTORY
CREATE TABLE public.material_stock (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  material_id uuid NOT NULL REFERENCES public.materials(id) ON DELETE CASCADE,
  factory_id uuid NOT NULL REFERENCES public.factories(id) ON DELETE CASCADE,
  current_stock numeric NOT NULL DEFAULT 0,
  reserved_stock numeric NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(material_id, factory_id)
);
ALTER TABLE public.material_stock ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage material stock" ON public.material_stock FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE TRIGGER trg_mstock_updated_at BEFORE UPDATE ON public.material_stock FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 4. STOCK INWARD (Purchase Entries)
CREATE TABLE public.stock_inwards (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  inward_number text NOT NULL DEFAULT '',
  factory_id uuid NOT NULL REFERENCES public.factories(id),
  supplier_id uuid REFERENCES public.suppliers(id),
  invoice_number text,
  invoice_date date,
  invoice_url text,
  vehicle_number text,
  total_amount numeric DEFAULT 0,
  qc_status text NOT NULL DEFAULT 'pending',
  qc_notes text,
  notes text,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.stock_inwards ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage stock inwards" ON public.stock_inwards FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE TRIGGER trg_inwards_updated_at BEFORE UPDATE ON public.stock_inwards FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE OR REPLACE FUNCTION public.generate_inward_number()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
DECLARE seq_num integer;
BEGIN
  IF NEW.inward_number IS NULL OR NEW.inward_number = '' THEN
    SELECT COALESCE(MAX(CAST(SUBSTRING(inward_number FROM 'IN-(\d+)') AS integer)), 1000) + 1 INTO seq_num FROM public.stock_inwards;
    NEW.inward_number := 'IN-' || seq_num;
  END IF;
  RETURN NEW;
END; $$;
CREATE TRIGGER trg_inward_num BEFORE INSERT ON public.stock_inwards FOR EACH ROW EXECUTE FUNCTION public.generate_inward_number();

CREATE TABLE public.stock_inward_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  inward_id uuid NOT NULL REFERENCES public.stock_inwards(id) ON DELETE CASCADE,
  material_id uuid NOT NULL REFERENCES public.materials(id),
  quantity numeric NOT NULL DEFAULT 0,
  rate numeric NOT NULL DEFAULT 0,
  amount numeric NOT NULL DEFAULT 0,
  qc_passed boolean DEFAULT true,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.stock_inward_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage stock inward items" ON public.stock_inward_items FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- 5. STOCK OUTWARD / CONSUMPTION
CREATE TABLE public.stock_outwards (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  outward_number text NOT NULL DEFAULT '',
  factory_id uuid NOT NULL REFERENCES public.factories(id),
  project_name text,
  project_id uuid,
  quotation_id uuid REFERENCES public.quotations(id) ON DELETE SET NULL,
  sales_order_id uuid REFERENCES public.sales_orders(id) ON DELETE SET NULL,
  purpose text NOT NULL DEFAULT 'production',
  issued_to text,
  notes text,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.stock_outwards ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage stock outwards" ON public.stock_outwards FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE TRIGGER trg_outwards_updated_at BEFORE UPDATE ON public.stock_outwards FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE OR REPLACE FUNCTION public.generate_outward_number()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
DECLARE seq_num integer;
BEGIN
  IF NEW.outward_number IS NULL OR NEW.outward_number = '' THEN
    SELECT COALESCE(MAX(CAST(SUBSTRING(outward_number FROM 'OUT-(\d+)') AS integer)), 1000) + 1 INTO seq_num FROM public.stock_outwards;
    NEW.outward_number := 'OUT-' || seq_num;
  END IF;
  RETURN NEW;
END; $$;
CREATE TRIGGER trg_outward_num BEFORE INSERT ON public.stock_outwards FOR EACH ROW EXECUTE FUNCTION public.generate_outward_number();

CREATE TABLE public.stock_outward_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  outward_id uuid NOT NULL REFERENCES public.stock_outwards(id) ON DELETE CASCADE,
  material_id uuid NOT NULL REFERENCES public.materials(id),
  quantity numeric NOT NULL DEFAULT 0,
  wastage numeric NOT NULL DEFAULT 0,
  rate numeric NOT NULL DEFAULT 0,
  amount numeric NOT NULL DEFAULT 0,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.stock_outward_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage stock outward items" ON public.stock_outward_items FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- 6. STOCK TRANSFERS BETWEEN FACTORIES
CREATE TABLE public.stock_transfers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  transfer_number text NOT NULL DEFAULT '',
  from_factory_id uuid NOT NULL REFERENCES public.factories(id),
  to_factory_id uuid NOT NULL REFERENCES public.factories(id),
  status text NOT NULL DEFAULT 'pending',
  vehicle_number text,
  driver_name text,
  notes text,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.stock_transfers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage stock transfers" ON public.stock_transfers FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE TRIGGER trg_transfers_updated_at BEFORE UPDATE ON public.stock_transfers FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE OR REPLACE FUNCTION public.generate_transfer_number()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
DECLARE seq_num integer;
BEGIN
  IF NEW.transfer_number IS NULL OR NEW.transfer_number = '' THEN
    SELECT COALESCE(MAX(CAST(SUBSTRING(transfer_number FROM 'TRF-(\d+)') AS integer)), 1000) + 1 INTO seq_num FROM public.stock_transfers;
    NEW.transfer_number := 'TRF-' || seq_num;
  END IF;
  RETURN NEW;
END; $$;
CREATE TRIGGER trg_transfer_num BEFORE INSERT ON public.stock_transfers FOR EACH ROW EXECUTE FUNCTION public.generate_transfer_number();

CREATE TABLE public.stock_transfer_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  transfer_id uuid NOT NULL REFERENCES public.stock_transfers(id) ON DELETE CASCADE,
  material_id uuid NOT NULL REFERENCES public.materials(id),
  quantity numeric NOT NULL DEFAULT 0,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.stock_transfer_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage stock transfer items" ON public.stock_transfer_items FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- 7. PROJECT MATERIAL ALLOCATIONS (BOQ)
CREATE TABLE public.project_allocations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  project_name text NOT NULL,
  client_name text,
  quotation_id uuid REFERENCES public.quotations(id) ON DELETE SET NULL,
  sales_order_id uuid REFERENCES public.sales_orders(id) ON DELETE SET NULL,
  factory_id uuid REFERENCES public.factories(id),
  status text NOT NULL DEFAULT 'planned',
  start_date date,
  end_date date,
  notes text,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.project_allocations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage project allocations" ON public.project_allocations FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE TRIGGER trg_palloc_updated_at BEFORE UPDATE ON public.project_allocations FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TABLE public.project_allocation_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  allocation_id uuid NOT NULL REFERENCES public.project_allocations(id) ON DELETE CASCADE,
  material_id uuid NOT NULL REFERENCES public.materials(id),
  planned_quantity numeric NOT NULL DEFAULT 0,
  issued_quantity numeric NOT NULL DEFAULT 0,
  rate numeric DEFAULT 0,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.project_allocation_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage project allocation items" ON public.project_allocation_items FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- 8. PURCHASE ORDERS
CREATE TABLE public.purchase_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  po_number text NOT NULL DEFAULT '',
  supplier_id uuid REFERENCES public.suppliers(id),
  factory_id uuid REFERENCES public.factories(id),
  status text NOT NULL DEFAULT 'pending',
  po_date date NOT NULL DEFAULT CURRENT_DATE,
  expected_delivery_date date,
  subtotal numeric DEFAULT 0,
  gst_amount numeric DEFAULT 0,
  total_amount numeric DEFAULT 0,
  notes text,
  terms text,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.purchase_orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage purchase orders" ON public.purchase_orders FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE TRIGGER trg_po_updated_at BEFORE UPDATE ON public.purchase_orders FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE OR REPLACE FUNCTION public.generate_po_number()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
DECLARE seq_num integer;
BEGIN
  IF NEW.po_number IS NULL OR NEW.po_number = '' THEN
    SELECT COALESCE(MAX(CAST(SUBSTRING(po_number FROM 'PO-(\d+)') AS integer)), 1000) + 1 INTO seq_num FROM public.purchase_orders;
    NEW.po_number := 'PO-' || seq_num;
  END IF;
  RETURN NEW;
END; $$;
CREATE TRIGGER trg_po_num BEFORE INSERT ON public.purchase_orders FOR EACH ROW EXECUTE FUNCTION public.generate_po_number();

CREATE TABLE public.purchase_order_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  po_id uuid NOT NULL REFERENCES public.purchase_orders(id) ON DELETE CASCADE,
  material_id uuid NOT NULL REFERENCES public.materials(id),
  quantity numeric NOT NULL DEFAULT 0,
  received_quantity numeric NOT NULL DEFAULT 0,
  rate numeric NOT NULL DEFAULT 0,
  amount numeric NOT NULL DEFAULT 0,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.purchase_order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage purchase order items" ON public.purchase_order_items FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- 9. RENTAL ASSETS (Cabins)
CREATE TABLE public.rental_assets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  cabin_id text NOT NULL UNIQUE,
  cabin_type text NOT NULL,
  size text,
  manufacture_date date,
  purchase_cost numeric DEFAULT 0,
  monthly_rent numeric DEFAULT 0,
  status text NOT NULL DEFAULT 'available',
  current_factory_id uuid REFERENCES public.factories(id),
  current_location text,
  qr_code text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.rental_assets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage rental assets" ON public.rental_assets FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE TRIGGER trg_rental_assets_updated_at BEFORE UPDATE ON public.rental_assets FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TABLE public.rental_assignments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  asset_id uuid NOT NULL REFERENCES public.rental_assets(id) ON DELETE CASCADE,
  customer_name text NOT NULL,
  customer_phone text,
  customer_email text,
  site_address text,
  dispatch_date date,
  expected_return_date date,
  actual_return_date date,
  monthly_rate numeric DEFAULT 0,
  deposit_amount numeric DEFAULT 0,
  status text NOT NULL DEFAULT 'active',
  damage_notes text,
  damage_charges numeric DEFAULT 0,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.rental_assignments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage rental assignments" ON public.rental_assignments FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE TRIGGER trg_rental_assign_updated_at BEFORE UPDATE ON public.rental_assignments FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TABLE public.rental_maintenance (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  asset_id uuid NOT NULL REFERENCES public.rental_assets(id) ON DELETE CASCADE,
  maintenance_date date NOT NULL DEFAULT CURRENT_DATE,
  maintenance_type text NOT NULL,
  description text,
  cost numeric DEFAULT 0,
  performed_by text,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.rental_maintenance ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage rental maintenance" ON public.rental_maintenance FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- 10. GATE PASS / VEHICLE DISPATCH
CREATE TABLE public.gate_passes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  gate_pass_number text NOT NULL DEFAULT '',
  pass_type text NOT NULL DEFAULT 'outward',
  factory_id uuid REFERENCES public.factories(id),
  pass_date date NOT NULL DEFAULT CURRENT_DATE,
  vehicle_number text,
  driver_name text,
  driver_phone text,
  destination text,
  customer_name text,
  purpose text,
  related_outward_id uuid REFERENCES public.stock_outwards(id) ON DELETE SET NULL,
  related_transfer_id uuid REFERENCES public.stock_transfers(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'pending',
  approved_by uuid,
  approved_at timestamptz,
  notes text,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.gate_passes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage gate passes" ON public.gate_passes FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE TRIGGER trg_gp_updated_at BEFORE UPDATE ON public.gate_passes FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE OR REPLACE FUNCTION public.generate_gate_pass_number()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
DECLARE seq_num integer;
BEGIN
  IF NEW.gate_pass_number IS NULL OR NEW.gate_pass_number = '' THEN
    SELECT COALESCE(MAX(CAST(SUBSTRING(gate_pass_number FROM 'GP-(\d+)') AS integer)), 1000) + 1 INTO seq_num FROM public.gate_passes;
    NEW.gate_pass_number := 'GP-' || seq_num;
  END IF;
  RETURN NEW;
END; $$;
CREATE TRIGGER trg_gp_num BEFORE INSERT ON public.gate_passes FOR EACH ROW EXECUTE FUNCTION public.generate_gate_pass_number();

-- 11. PRODUCTION LOGS (Daily)
CREATE TABLE public.production_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  log_date date NOT NULL DEFAULT CURRENT_DATE,
  factory_id uuid NOT NULL REFERENCES public.factories(id),
  product_type text NOT NULL,
  quantity_produced numeric NOT NULL DEFAULT 0,
  shift text,
  supervisor_name text,
  project_name text,
  notes text,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.production_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage production logs" ON public.production_logs FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE TRIGGER trg_prod_updated_at BEFORE UPDATE ON public.production_logs FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 12. SCRAP RECORDS
CREATE TABLE public.scrap_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  scrap_date date NOT NULL DEFAULT CURRENT_DATE,
  factory_id uuid REFERENCES public.factories(id),
  material_name text NOT NULL,
  quantity numeric NOT NULL DEFAULT 0,
  unit text DEFAULT 'kg',
  rate numeric DEFAULT 0,
  total_amount numeric DEFAULT 0,
  buyer_name text,
  buyer_phone text,
  status text NOT NULL DEFAULT 'pending',
  notes text,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.scrap_records ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage scrap records" ON public.scrap_records FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE TRIGGER trg_scrap_updated_at BEFORE UPDATE ON public.scrap_records FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 13. MATERIAL APPROVAL WORKFLOW
CREATE TABLE public.material_approvals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  request_type text NOT NULL,
  reference_id uuid,
  reference_number text,
  requested_by uuid,
  requested_at timestamptz NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'pending',
  approved_by uuid,
  approved_at timestamptz,
  rejection_reason text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.material_approvals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage material approvals" ON public.material_approvals FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE TRIGGER trg_mapprov_updated_at BEFORE UPDATE ON public.material_approvals FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================
-- HELPER FUNCTION: adjust stock atomically
-- ============================================================
CREATE OR REPLACE FUNCTION public.adjust_material_stock(
  _material_id uuid,
  _factory_id uuid,
  _delta numeric
) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.material_stock (material_id, factory_id, current_stock)
  VALUES (_material_id, _factory_id, _delta)
  ON CONFLICT (material_id, factory_id)
  DO UPDATE SET current_stock = public.material_stock.current_stock + _delta,
                updated_at = now();
END; $$;


-- ===== 20260506025424_231660b9-1f29-45f7-aff3-89e54d5e761d.sql ============================================
-- Add team_name to scrap_records
ALTER TABLE public.scrap_records ADD COLUMN IF NOT EXISTS team_name text;

-- Add workflow tracking to production_logs
ALTER TABLE public.production_logs 
  ADD COLUMN IF NOT EXISTS department_progress jsonb NOT NULL DEFAULT '{"welding":0,"painting":0,"electrical":0,"carpentry":0,"furniture":0,"finishing":0}'::jsonb,
  ADD COLUMN IF NOT EXISTS is_ready_for_dispatch boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS workflow_status text NOT NULL DEFAULT 'in_progress';

-- Work Orders module
CREATE TABLE IF NOT EXISTS public.work_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  wo_number text NOT NULL DEFAULT '',
  wo_date date NOT NULL DEFAULT CURRENT_DATE,
  factory_id uuid,
  project_name text NOT NULL,
  client_name text,
  client_phone text,
  product_type text NOT NULL,
  quantity numeric NOT NULL DEFAULT 1,
  size text,
  specifications text,
  start_date date,
  target_date date,
  priority text NOT NULL DEFAULT 'medium',
  status text NOT NULL DEFAULT 'pending',
  assigned_supervisor text,
  notes text,
  sales_order_id uuid,
  quotation_id uuid,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.work_orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage work orders" ON public.work_orders
  FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

CREATE OR REPLACE FUNCTION public.generate_wo_number()
RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public' AS $$
DECLARE seq_num integer;
BEGIN
  IF NEW.wo_number IS NULL OR NEW.wo_number = '' THEN
    SELECT COALESCE(MAX(CAST(SUBSTRING(wo_number FROM 'WO-(\d+)') AS integer)), 1000) + 1 INTO seq_num FROM public.work_orders;
    NEW.wo_number := 'WO-' || seq_num;
  END IF;
  RETURN NEW;
END; $$;

CREATE TRIGGER work_orders_number_trg BEFORE INSERT ON public.work_orders
  FOR EACH ROW EXECUTE FUNCTION public.generate_wo_number();

CREATE TRIGGER work_orders_updated_at BEFORE UPDATE ON public.work_orders
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ===== 20260506030450_0ee4ad29-667c-47d7-92b5-9349deb5902c.sql ============================================

-- Parties (client master)
CREATE TABLE public.parties (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  company text,
  email text,
  phone text,
  gstin text,
  pan text,
  billing_address text,
  city text,
  state text,
  pincode text,
  party_type text NOT NULL DEFAULT 'customer', -- customer | supplier | both
  credit_limit numeric NOT NULL DEFAULT 0,
  opening_balance numeric NOT NULL DEFAULT 0,
  notes text,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_parties_name ON public.parties(name);
CREATE INDEX idx_parties_phone ON public.parties(phone);

ALTER TABLE public.parties ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage parties" ON public.parties
  FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

CREATE TRIGGER update_parties_updated_at BEFORE UPDATE ON public.parties
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Multiple ship-to / project addresses per party
CREATE TABLE public.party_addresses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  party_id uuid NOT NULL REFERENCES public.parties(id) ON DELETE CASCADE,
  label text NOT NULL, -- e.g. "Site 1 - Hosur", "HO Office"
  contact_person text,
  contact_phone text,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  pincode text,
  is_default boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_party_addresses_party ON public.party_addresses(party_id);

ALTER TABLE public.party_addresses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage party addresses" ON public.party_addresses
  FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- Link existing transactions to party (nullable, non-breaking)
ALTER TABLE public.quotations          ADD COLUMN party_id uuid REFERENCES public.parties(id);
ALTER TABLE public.sales_orders        ADD COLUMN party_id uuid REFERENCES public.parties(id);
ALTER TABLE public.project_allocations ADD COLUMN party_id uuid REFERENCES public.parties(id);
ALTER TABLE public.rental_assignments  ADD COLUMN party_id uuid REFERENCES public.parties(id);
ALTER TABLE public.stock_outwards      ADD COLUMN party_id uuid REFERENCES public.parties(id);

CREATE INDEX idx_quotations_party  ON public.quotations(party_id);
CREATE INDEX idx_so_party          ON public.sales_orders(party_id);
CREATE INDEX idx_proj_alloc_party  ON public.project_allocations(party_id);
CREATE INDEX idx_rentals_party     ON public.rental_assignments(party_id);


-- ===== 20260506032338_da1f79f6-97db-4783-90d6-6b300f0df48d.sql ============================================

CREATE TABLE public.ledger_entries (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  party_id UUID NOT NULL REFERENCES public.parties(id) ON DELETE CASCADE,
  entry_date DATE NOT NULL DEFAULT CURRENT_DATE,
  entry_type TEXT NOT NULL DEFAULT 'payment',
  project_ref TEXT,
  reference_number TEXT,
  description TEXT,
  debit NUMERIC NOT NULL DEFAULT 0,
  credit NUMERIC NOT NULL DEFAULT 0,
  payment_mode TEXT,
  notes TEXT,
  created_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.ledger_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage ledger entries"
ON public.ledger_entries FOR ALL TO authenticated
USING (is_admin()) WITH CHECK (is_admin());

CREATE INDEX idx_ledger_entries_party ON public.ledger_entries(party_id);
CREATE INDEX idx_ledger_entries_date ON public.ledger_entries(entry_date DESC);

CREATE TRIGGER update_ledger_entries_updated_at
BEFORE UPDATE ON public.ledger_entries
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


-- ===== 20260506033059_36328b4d-311b-4e7f-8b9d-29b3cdf1f179.sql ============================================

ALTER TABLE public.rental_assignments
  ADD COLUMN IF NOT EXISTS deposit_refunded_amount NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS deposit_refund_date DATE,
  ADD COLUMN IF NOT EXISTS deposit_status TEXT NOT NULL DEFAULT 'held';


-- ===== 20260506160831_6d7d211e-10ff-4062-ad56-8d4873f24a5d.sql ============================================
-- Extend products table with Google Merchant fields (only add if missing)
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS brand text DEFAULT 'Portable Office Cabin',
  ADD COLUMN IF NOT EXISTS gtin text,
  ADD COLUMN IF NOT EXISTS mpn text,
  ADD COLUMN IF NOT EXISTS condition text DEFAULT 'new',
  ADD COLUMN IF NOT EXISTS google_product_category text,
  ADD COLUMN IF NOT EXISTS product_type text,
  ADD COLUMN IF NOT EXISTS additional_image_urls text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS sale_price numeric,
  ADD COLUMN IF NOT EXISTS sale_price_effective_from timestamptz,
  ADD COLUMN IF NOT EXISTS sale_price_effective_to timestamptz,
  ADD COLUMN IF NOT EXISTS currency text DEFAULT 'INR',
  ADD COLUMN IF NOT EXISTS color text,
  ADD COLUMN IF NOT EXISTS size text,
  ADD COLUMN IF NOT EXISTS material text,
  ADD COLUMN IF NOT EXISTS pattern text,
  ADD COLUMN IF NOT EXISTS age_group text,
  ADD COLUMN IF NOT EXISTS gender text,
  ADD COLUMN IF NOT EXISTS item_group_id text,
  ADD COLUMN IF NOT EXISTS shipping_weight_kg numeric,
  ADD COLUMN IF NOT EXISTS shipping_length_cm numeric,
  ADD COLUMN IF NOT EXISTS shipping_width_cm numeric,
  ADD COLUMN IF NOT EXISTS shipping_height_cm numeric,
  ADD COLUMN IF NOT EXISTS identifier_exists boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS custom_label_0 text,
  ADD COLUMN IF NOT EXISTS custom_label_1 text,
  ADD COLUMN IF NOT EXISTS custom_label_2 text,
  ADD COLUMN IF NOT EXISTS custom_label_3 text,
  ADD COLUMN IF NOT EXISTS custom_label_4 text,
  ADD COLUMN IF NOT EXISTS meta_title text,
  ADD COLUMN IF NOT EXISTS meta_description text,
  ADD COLUMN IF NOT EXISTS meta_keywords text;

-- Extend categories table
ALTER TABLE public.categories
  ADD COLUMN IF NOT EXISTS google_product_category text,
  ADD COLUMN IF NOT EXISTS meta_title text,
  ADD COLUMN IF NOT EXISTS meta_description text,
  ADD COLUMN IF NOT EXISTS meta_keywords text;

-- Product variants table
CREATE TABLE IF NOT EXISTS public.product_variants (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  sku text,
  gtin text,
  mpn text,
  title text,
  price numeric,
  sale_price numeric,
  currency text DEFAULT 'INR',
  stock_quantity integer NOT NULL DEFAULT 0,
  in_stock boolean NOT NULL DEFAULT true,
  color text,
  size text,
  material text,
  pattern text,
  image_url text,
  item_group_id text,
  sort_order integer DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view variants" ON public.product_variants;
CREATE POLICY "Anyone can view variants" ON public.product_variants FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admins manage variants" ON public.product_variants;
CREATE POLICY "Admins manage variants" ON public.product_variants FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

CREATE TRIGGER trg_variants_updated BEFORE UPDATE ON public.product_variants
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Product reviews table
CREATE TABLE IF NOT EXISTS public.product_reviews (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  rating integer NOT NULL CHECK (rating BETWEEN 1 AND 5),
  title text,
  body text,
  reviewer_name text NOT NULL,
  reviewer_email text,
  verified_purchase boolean NOT NULL DEFAULT false,
  helpful_count integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.product_reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view approved reviews" ON public.product_reviews;
CREATE POLICY "Anyone can view approved reviews" ON public.product_reviews FOR SELECT USING (status = 'approved');
DROP POLICY IF EXISTS "Anyone can submit reviews" ON public.product_reviews;
CREATE POLICY "Anyone can submit reviews" ON public.product_reviews FOR INSERT WITH CHECK (status = 'pending');
DROP POLICY IF EXISTS "Admins manage reviews" ON public.product_reviews;
CREATE POLICY "Admins manage reviews" ON public.product_reviews FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

CREATE TRIGGER trg_reviews_updated BEFORE UPDATE ON public.product_reviews
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Pages (CMS) table
CREATE TABLE IF NOT EXISTS public.pages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  content text,
  excerpt text,
  featured_image_url text,
  meta_title text,
  meta_description text,
  meta_keywords text,
  status text NOT NULL DEFAULT 'draft',
  published_at timestamptz,
  sort_order integer DEFAULT 0,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.pages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view published pages" ON public.pages;
CREATE POLICY "Anyone can view published pages" ON public.pages FOR SELECT USING (status = 'published');
DROP POLICY IF EXISTS "Admins manage pages" ON public.pages;
CREATE POLICY "Admins manage pages" ON public.pages FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

CREATE TRIGGER trg_pages_updated BEFORE UPDATE ON public.pages
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_variants_product ON public.product_variants(product_id);
CREATE INDEX IF NOT EXISTS idx_reviews_product ON public.product_reviews(product_id);
CREATE INDEX IF NOT EXISTS idx_pages_slug ON public.pages(slug);

-- ===== 20260507100945_d481efd5-64ed-4b70-841f-16e10f24f1d2.sql ============================================

-- Settings (single row)
CREATE TABLE public.factory_tracker_settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  theft_detection_enabled boolean NOT NULL DEFAULT true,
  warning_threshold_percent numeric NOT NULL DEFAULT 10,
  alert_threshold_percent numeric NOT NULL DEFAULT 25,
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.factory_tracker_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage factory tracker settings" ON public.factory_tracker_settings FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
INSERT INTO public.factory_tracker_settings (theft_detection_enabled) VALUES (true);

-- Invoices
CREATE TABLE public.factory_invoices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_number text NOT NULL,
  invoice_date date NOT NULL DEFAULT CURRENT_DATE,
  supplier_name text,
  notes text,
  status text NOT NULL DEFAULT 'pending',
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.factory_invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage factory invoices" ON public.factory_invoices FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE TRIGGER trg_factory_invoices_updated BEFORE UPDATE ON public.factory_invoices FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Materials (per invoice)
CREATE TABLE public.factory_invoice_materials (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id uuid REFERENCES public.factory_invoices(id) ON DELETE CASCADE,
  category text NOT NULL,
  name text NOT NULL,
  unit text NOT NULL,
  ordered numeric NOT NULL DEFAULT 0,
  received numeric NOT NULL DEFAULT 0,
  used numeric NOT NULL DEFAULT 0,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.factory_invoice_materials ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage factory invoice materials" ON public.factory_invoice_materials FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE TRIGGER trg_factory_invoice_materials_updated BEFORE UPDATE ON public.factory_invoice_materials FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE INDEX idx_factory_invoice_materials_invoice ON public.factory_invoice_materials(invoice_id);
CREATE INDEX idx_factory_invoice_materials_category ON public.factory_invoice_materials(category);


-- ===== 20260507103522_55048499-64a3-4f80-9931-4fefff90bb6b.sql ============================================

CREATE TABLE public.cabin_quotations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  quotation_number text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'draft',
  client_name text,
  client_company text,
  client_phone text,
  client_email text,
  site_address text,
  spec jsonb NOT NULL DEFAULT '{}'::jsonb,
  bom jsonb NOT NULL DEFAULT '[]'::jsonb,
  totals jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.cabin_quotations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage cabin quotations" ON public.cabin_quotations
  FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

CREATE TRIGGER trg_cabin_quotations_updated
  BEFORE UPDATE ON public.cabin_quotations
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE SEQUENCE IF NOT EXISTS public.cabin_quotation_seq START 1000;

CREATE OR REPLACE FUNCTION public.gen_cabin_quotation_number()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF NEW.quotation_number IS NULL OR NEW.quotation_number = '' THEN
    NEW.quotation_number := 'CQ-' || nextval('public.cabin_quotation_seq');
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER trg_cabin_quotations_number
  BEFORE INSERT ON public.cabin_quotations
  FOR EACH ROW EXECUTE FUNCTION public.gen_cabin_quotation_number();

CREATE TABLE public.cabin_material_rates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  item_key text NOT NULL UNIQUE,
  name text NOT NULL,
  unit text NOT NULL,
  rate numeric NOT NULL DEFAULT 0,
  wastage_percent numeric NOT NULL DEFAULT 10,
  gst_percent numeric NOT NULL DEFAULT 18,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.cabin_material_rates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage cabin material rates" ON public.cabin_material_rates
  FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "Anyone can view cabin material rates" ON public.cabin_material_rates
  FOR SELECT USING (true);


-- ===== 20260507115615_8521bf71-95d6-4677-bba7-ab34eebcd207.sql ============================================

-- Function to seed material_stock from opening_stock
CREATE OR REPLACE FUNCTION public.seed_material_stock()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  default_factory uuid;
BEGIN
  IF NEW.opening_stock IS NULL OR NEW.opening_stock = 0 THEN
    RETURN NEW;
  END IF;
  SELECT id INTO default_factory FROM public.factories WHERE is_active = true ORDER BY code LIMIT 1;
  IF default_factory IS NULL THEN
    RETURN NEW;
  END IF;
  INSERT INTO public.material_stock (material_id, factory_id, current_stock)
  VALUES (NEW.id, default_factory, NEW.opening_stock)
  ON CONFLICT DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_seed_material_stock ON public.materials;
CREATE TRIGGER trg_seed_material_stock
AFTER INSERT ON public.materials
FOR EACH ROW
EXECUTE FUNCTION public.seed_material_stock();

-- Backfill existing materials with no stock entry
INSERT INTO public.material_stock (material_id, factory_id, current_stock)
SELECT m.id,
       (SELECT id FROM public.factories WHERE is_active=true ORDER BY code LIMIT 1),
       m.opening_stock
FROM public.materials m
WHERE m.opening_stock > 0
  AND NOT EXISTS (SELECT 1 FROM public.material_stock ms WHERE ms.material_id = m.id)
  AND EXISTS (SELECT 1 FROM public.factories WHERE is_active=true);


-- ===== 20260507133741_ab5fb727-e8d3-4662-99d8-8d318feb9e1b.sql ============================================
ALTER TABLE public.party_addresses
  ADD COLUMN IF NOT EXISTS company text,
  ADD COLUMN IF NOT EXISTS gstin text,
  ADD COLUMN IF NOT EXISTS consignee_name text;

-- ===== 20260507133811_232566a8-dad8-4be9-8b35-175ab319790a.sql ============================================
ALTER TABLE public.parties
  ADD COLUMN IF NOT EXISTS contact_person text,
  ADD COLUMN IF NOT EXISTS site_location text;

-- ===== 20260507155816_2b181428-a8d7-44ff-9712-9a559c410a45.sql ============================================
-- Add safety_stock to materials (permanent stock = existing opening_stock; inward stock is computed)
ALTER TABLE public.materials ADD COLUMN IF NOT EXISTS safety_stock numeric NOT NULL DEFAULT 0;

-- Machinery Sections master
CREATE TABLE IF NOT EXISTS public.machinery_sections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.machinery_sections ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage machinery sections" ON public.machinery_sections FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- Contractors master
CREATE TABLE IF NOT EXISTS public.contractors (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  company text,
  phone text,
  email text,
  address text,
  gstin text,
  notes text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.contractors ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage contractors" ON public.contractors FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- Machinery master
CREATE TABLE IF NOT EXISTS public.machinery (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  code text,
  section_id uuid REFERENCES public.machinery_sections(id) ON DELETE SET NULL,
  brand text,
  model text,
  serial_number text,
  total_quantity numeric NOT NULL DEFAULT 1,
  available_quantity numeric NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'available',
  purchase_date date,
  purchase_value numeric,
  notes text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.machinery ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage machinery" ON public.machinery FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- Machinery handovers (transactions)
CREATE TABLE IF NOT EXISTS public.machinery_handovers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  machinery_id uuid NOT NULL REFERENCES public.machinery(id) ON DELETE CASCADE,
  contractor_id uuid NOT NULL REFERENCES public.contractors(id) ON DELETE CASCADE,
  section_id uuid REFERENCES public.machinery_sections(id) ON DELETE SET NULL,
  quantity numeric NOT NULL DEFAULT 1,
  issue_date date NOT NULL DEFAULT CURRENT_DATE,
  expected_return_date date,
  return_date date,
  condition_out text,
  condition_in text,
  site_location text,
  status text NOT NULL DEFAULT 'issued',
  issued_by_name text,
  received_by_name text,
  notes text,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.machinery_handovers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage machinery handovers" ON public.machinery_handovers FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

CREATE TRIGGER trg_machinery_sections_updated BEFORE UPDATE ON public.machinery_sections FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trg_contractors_updated BEFORE UPDATE ON public.contractors FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trg_machinery_updated BEFORE UPDATE ON public.machinery FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trg_machinery_handovers_updated BEFORE UPDATE ON public.machinery_handovers FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ===== 20260507162540_89a26cb1-82fc-411a-9f52-934705088e03.sql ============================================
ALTER TABLE public.materials ADD COLUMN IF NOT EXISTS material_type text NOT NULL DEFAULT 'inward';

-- ===== 20260605152228_358390f9-958d-4580-8970-3f6e37ea9c4e.sql ============================================
ALTER TABLE public.product_reviews DROP CONSTRAINT IF EXISTS product_reviews_product_id_fkey;
ALTER TABLE public.product_reviews ALTER COLUMN product_id DROP NOT NULL;
ALTER TABLE public.product_reviews ADD COLUMN IF NOT EXISTS product_slug text;
ALTER TABLE public.product_reviews ADD COLUMN IF NOT EXISTS reviewer_phone text;
CREATE INDEX IF NOT EXISTS idx_reviews_product_slug ON public.product_reviews(product_slug);
GRANT SELECT, INSERT ON public.product_reviews TO anon;
GRANT SELECT, INSERT ON public.product_reviews TO authenticated;
GRANT ALL ON public.product_reviews TO service_role;

-- ===== 20260605153956_b449e9f9-348a-404c-bf1e-a6fb14a657cb.sql ============================================
CREATE POLICY "Public can read review otp setting"
ON public.site_settings
FOR SELECT
TO anon, authenticated
USING (key = 'reviews_require_otp');

GRANT SELECT ON public.site_settings TO anon;
GRANT SELECT ON public.site_settings TO authenticated;

-- ===== 20260606103531_12f93e3f-d5f0-4bf3-8617-cce0419f18fc.sql ============================================

CREATE POLICY "Public can view product images"
ON storage.objects FOR SELECT TO public
USING (bucket_id = 'product-images');

CREATE POLICY "Authenticated can upload product images"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'product-images');

CREATE POLICY "Authenticated can update product images"
ON storage.objects FOR UPDATE TO authenticated
USING (bucket_id = 'product-images');

CREATE POLICY "Authenticated can delete product images"
ON storage.objects FOR DELETE TO authenticated
USING (bucket_id = 'product-images');


-- ===== 20260606164023_c72dcf18-924d-4a17-8445-f5d12ca33c27.sql ============================================

-- 1) Hide reviewer PII (email, phone) from public/authenticated reads
REVOKE SELECT (reviewer_email, reviewer_phone) ON public.product_reviews FROM anon;
REVOKE SELECT (reviewer_email, reviewer_phone) ON public.product_reviews FROM authenticated;
GRANT SELECT (reviewer_email, reviewer_phone) ON public.product_reviews TO service_role;

-- 2) Admin-only RPC to fetch full reviews (incl. PII) — uses SECURITY DEFINER + is_admin() gate
CREATE OR REPLACE FUNCTION public.admin_list_reviews(_status text DEFAULT NULL)
RETURNS SETOF public.product_reviews
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;
  RETURN QUERY
    SELECT * FROM public.product_reviews
    WHERE _status IS NULL OR status = _status
    ORDER BY created_at DESC;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.admin_list_reviews(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_list_reviews(text) TO authenticated, service_role;

-- 3) Restrict product-images storage writes/updates/deletes to admins only
DROP POLICY IF EXISTS "Authenticated can upload product images" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated can update product images" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated can delete product images" ON storage.objects;

CREATE POLICY "Admins can upload product images"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'product-images' AND public.is_admin());

CREATE POLICY "Admins can update product images"
  ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'product-images' AND public.is_admin())
  WITH CHECK (bucket_id = 'product-images' AND public.is_admin());

CREATE POLICY "Admins can delete product images"
  ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'product-images' AND public.is_admin());


-- ===== 20260615120000_create_blog_posts.sql ============================================
-- Blog posts table for admin-managed articles (CRM → Blog Posts)
CREATE TABLE IF NOT EXISTS public.blog_posts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  excerpt text,
  content text,
  featured_image_url text,
  meta_title text,
  meta_description text,
  meta_keywords text,
  author text NOT NULL DEFAULT 'Portable Office Cabin',
  category text NOT NULL DEFAULT 'Industry Insights',
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
  featured boolean NOT NULL DEFAULT false,
  published_at timestamptz,
  sort_order integer DEFAULT 0,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view published blog posts" ON public.blog_posts;
CREATE POLICY "Anyone can view published blog posts"
  ON public.blog_posts
  FOR SELECT
  USING (status = 'published');

DROP POLICY IF EXISTS "Admins manage blog posts" ON public.blog_posts;
CREATE POLICY "Admins manage blog posts"
  ON public.blog_posts
  FOR ALL
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP TRIGGER IF EXISTS trg_blog_posts_updated ON public.blog_posts;
CREATE TRIGGER trg_blog_posts_updated
  BEFORE UPDATE ON public.blog_posts
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_blog_posts_slug ON public.blog_posts(slug);
CREATE INDEX IF NOT EXISTS idx_blog_posts_status ON public.blog_posts(status);
CREATE INDEX IF NOT EXISTS idx_blog_posts_published_at ON public.blog_posts(published_at DESC NULLS LAST);

-- Optional: migrate any existing CMS rows tagged as blog content in pages (none by default)
-- INSERT INTO public.blog_posts (slug, title, excerpt, content, featured_image_url, meta_title, meta_description, meta_keywords, status, published_at, sort_order, created_by, created_at, updated_at)
-- SELECT slug, title, excerpt, content, featured_image_url, meta_title, meta_description, meta_keywords, status, published_at, sort_order, created_by, created_at, updated_at
-- FROM public.pages
-- ON CONFLICT (slug) DO NOTHING;


-- ===== 20260630120000_quotation_advance_balance.sql ============================================
-- Quotation Pro: record advance payment received and the remaining customer balance.
-- advance_paid  = resolved rupee amount already paid by the customer
-- balance_due   = total_amount - advance_paid (snapshot stored at save time)
ALTER TABLE public.quotations
  ADD COLUMN IF NOT EXISTS advance_paid numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS balance_due numeric;

