"use client";

import type { LabourColonyResult, RoomFloorPlanConfig, ElevationRoofConfig } from "@/lib/quotation/labourColony";
import { buildElevation, resolveRoof, type ElevationGeom, type ElevationFace } from "@/lib/quotation/elevation";
import { formatLen, type LengthUnit } from "@/lib/quotation/units";

/**
 * Four ELEVATIONS (Front / Rear / Left / Right) for the Labour Colony calculator.
 *
 * Every face is generated by buildElevation(), which derives its geometry from the SAME
 * buildRoomFloorPlan() output the 2D room-wise floor plan renders — so the elevations update
 * live with every calculator change (rooms, floors, sizes, doors/windows, verandas, railing,
 * staircases, units) and can never disagree with the plan. Roof type/rise and plinth height
 * are drawing-only settings. Schematic reference, not stamped CAD.
 */

const COL = {
  wall: "#334155", body: "#f8fafc", plinth: "#cbd5e1", roof: "#cbd5e1",
  door: "#dc2626", doorFill: "#fee2e2", window: "#2563eb", windowFill: "#dbeafe",
  floor: "#94a3b8", rail: "#059669", stair: "#b45309", stairFill: "#fde68a",
  dim: "#475569", overall: "#0369a1",
};

const FACES: { face: ElevationFace; title: string }[] = [
  { face: "front", title: "Front Elevation" },
  { face: "rear", title: "Rear Elevation" },
  { face: "left", title: "Left Side Elevation" },
  { face: "right", title: "Right Side Elevation" },
];

export function LabourColonyDrawings({ result, unit, floorPlan, onFloorPlanChange, plinthM }: {
  result: LabourColonyResult;
  unit: LengthUnit;
  floorPlan?: RoomFloorPlanConfig;
  onFloorPlanChange?: (fp: RoomFloorPlanConfig) => void;
  plinthM?: number;
}) {
  const fmt = (m: number) => formatLen(m, unit);
  const roof = resolveRoof(floorPlan);
  const setRoof = (patch: Partial<ElevationRoofConfig>) =>
    onFloorPlanChange?.({ ...(floorPlan ?? {}), roof: { ...(floorPlan?.roof ?? {}), ...patch } });

  return (
    <div className="space-y-4">
      {/* roof / plinth controls (drawing-only) */}
      <div className="flex flex-wrap items-end gap-3 rounded-xl border bg-slate-50 p-3 text-xs">
        <label className="font-medium text-slate-600">
          <span className="mb-1 block">Roof type</span>
          <select value={roof.type} onChange={(e) => setRoof({ type: e.target.value as ElevationRoofConfig["type"] })}
            className="h-8 rounded-md border border-slate-300 bg-white px-2 text-sm" disabled={!onFloorPlanChange}>
            <option value="gable">Gable (ridge along length)</option>
            <option value="hip">Hip</option>
            <option value="mono">Mono slope</option>
            <option value="flat">Flat</option>
          </select>
        </label>
        {roof.type !== "flat" && (
          <label className="font-medium text-slate-600">
            <span className="mb-1 block">Roof rise (m)</span>
            <input type="number" step={0.1} min={0.2} value={roof.riseM}
              onChange={(e) => setRoof({ riseM: Math.max(0.2, parseFloat(e.target.value) || 0.7) })}
              onFocus={(e) => e.currentTarget.select()} disabled={!onFloorPlanChange}
              className="h-8 w-24 rounded-md border border-slate-300 bg-white px-2 text-sm" />
          </label>
        )}
        <div className="ml-auto text-[11px] text-slate-500">
          Plinth {fmt(plinthM ?? 0.45)} (from Civil tab) · elevations derive from the room-wise floor plan — always in sync
        </div>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
        {FACES.map(({ face, title }) => {
          const g = buildElevation(result, floorPlan, face, { plinthM });
          return (
            <div key={face} className="rounded-2xl border bg-white p-4">
              <div className="mb-2">
                <div className="font-display font-bold text-sm text-slate-800">{title}</div>
                <div className="text-xs text-slate-500">
                  {fmt(g.totalWidthM)} wide · {fmt(g.totalHM)} high · {g.floors} floor{g.floors > 1 ? "s" : ""} · roof: {g.roof.type}
                </div>
              </div>
              <div className="overflow-x-auto">
                <ElevationSvg g={g} fmt={fmt} />
              </div>
            </div>
          );
        })}
      </div>

      <div className="flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-slate-600">
        <span className="flex items-center gap-1"><span className="inline-block h-2 w-4 border" style={{ background: COL.windowFill, borderColor: COL.window }} /> Window</span>
        <span className="flex items-center gap-1"><span className="inline-block h-2 w-4 border" style={{ background: COL.doorFill, borderColor: COL.door }} /> Door</span>
        <span className="flex items-center gap-1"><span className="inline-block h-0.5 w-4" style={{ background: COL.rail }} /> Safety railing</span>
        <span className="flex items-center gap-1"><span className="inline-block h-2.5 w-2.5 rounded-sm border" style={{ background: COL.stairFill, borderColor: COL.stair }} /> Staircase</span>
        <span className="flex items-center gap-1"><span className="inline-block h-2.5 w-2.5 rounded-sm border" style={{ background: COL.plinth, borderColor: COL.wall }} /> Plinth</span>
        <span className="text-slate-400">Derived from the floor plan · schematic reference</span>
      </div>
    </div>
  );
}

/* ================================================================ SVG face */

function ElevationSvg({ g, fmt }: { g: ElevationGeom; fmt: (m: number) => string }) {
  const spanX = Math.max(1, g.x1 - g.x0);
  const S = Math.min(30, Math.max(8, 620 / spanX)); // px per metre
  const PADX = 56, PADY = 34;
  const X = (m: number) => (m - g.x0) * S;
  const H = g.plinthM + g.bodyHM;                    // wall height above ground
  const Ytop = g.roof.riseM;                         // roof band sits above the walls
  const Y = (mFromGround: number) => PADY + (Ytop + H - mFromGround) * S;

  const svgW = spanX * S + PADX * 2;
  const svgH = (Ytop + H) * S + PADY * 2 + 26;

  const bodyW = g.bodyX1 - g.bodyX0;
  const groundY = Y(0);

  /* roof outline over the body (+overhang) */
  const rx0 = X(g.bodyX0 - g.roof.overhangM), rx1 = X(g.bodyX1 + g.roof.overhangM);
  const eaveY = Y(H), ridgeY = Y(H + g.roof.riseM - (g.roof.type === "flat" ? 0 : 0));
  let roofEl: React.ReactNode;
  if (g.roof.type === "flat") {
    roofEl = <rect x={rx0} y={eaveY - Math.max(2, 0.15 * S)} width={rx1 - rx0} height={Math.max(2, 0.15 * S)} fill={COL.roof} stroke={COL.wall} strokeWidth={1.2} />;
  } else if (g.roof.type === "mono") {
    roofEl = <polygon points={`${rx0},${eaveY} ${rx1},${eaveY} ${rx1},${ridgeY}`} fill={COL.roof} stroke={COL.wall} strokeWidth={1.2} />;
  } else if (g.face === "left" || g.face === "right") {
    // gable/hip seen from the side: triangle (hip slightly truncated)
    const mid = (rx0 + rx1) / 2;
    roofEl = g.roof.type === "hip"
      ? <polygon points={`${rx0},${eaveY} ${mid - 0.08 * (rx1 - rx0)},${ridgeY} ${mid + 0.08 * (rx1 - rx0)},${ridgeY} ${rx1},${eaveY}`} fill={COL.roof} stroke={COL.wall} strokeWidth={1.2} />
      : <polygon points={`${rx0},${eaveY} ${mid},${ridgeY} ${rx1},${eaveY}`} fill={COL.roof} stroke={COL.wall} strokeWidth={1.2} />;
  } else {
    // long faces: gable shows the ridge band; hip shows a trapezoid
    roofEl = g.roof.type === "hip"
      ? <polygon points={`${rx0},${eaveY} ${rx0 + 0.15 * (rx1 - rx0)},${ridgeY} ${rx1 - 0.15 * (rx1 - rx0)},${ridgeY} ${rx1},${eaveY}`} fill={COL.roof} stroke={COL.wall} strokeWidth={1.2} />
      : (
        <g>
          <rect x={rx0} y={ridgeY} width={rx1 - rx0} height={eaveY - ridgeY} fill={COL.roof} stroke={COL.wall} strokeWidth={1.2} />
          <line x1={rx0} y1={ridgeY} x2={rx1} y2={ridgeY} stroke={COL.wall} strokeWidth={1.6} />
        </g>
      );
  }

  return (
    <svg viewBox={`0 0 ${svgW} ${svgH}`} className="w-full h-auto" style={{ minWidth: Math.min(svgW, 640) }}>
      <g transform={`translate(${PADX},0)`}>
        {roofEl}

        {/* plinth band + wall body */}
        <rect x={X(g.bodyX0)} y={Y(g.plinthM)} width={bodyW * S} height={g.bodyHM * S} fill={COL.body} stroke={COL.wall} strokeWidth={1.8} />
        <rect x={X(g.bodyX0)} y={Y(0) - g.plinthM * S} width={bodyW * S} height={g.plinthM * S} fill={COL.plinth} stroke={COL.wall} strokeWidth={1.2} />

        {/* floor lines */}
        {Array.from({ length: g.floors - 1 }, (_, f) => (
          <line key={f} x1={X(g.bodyX0)} y1={Y(g.plinthM + (f + 1) * g.floorHM)} x2={X(g.bodyX1)} y2={Y(g.plinthM + (f + 1) * g.floorHM)}
            stroke={COL.floor} strokeWidth={1} strokeDasharray="5 3" />
        ))}

        {/* openings — true positions/sizes per floor */}
        {g.openings.map((o, i) => {
          const yBase = g.plinthM + o.floor * g.floorHM;
          const oy = Y(yBase + o.sillM + o.hM);
          const isDoor = o.kind === "door";
          return (
            <g key={i}>
              <rect x={X(o.x0)} y={oy} width={o.wM * S} height={o.hM * S}
                fill={isDoor ? COL.doorFill : COL.windowFill} stroke={isDoor ? COL.door : COL.window} strokeWidth={1.4} />
              {!isDoor && (
                <g stroke={COL.window} strokeWidth={0.7}>
                  <line x1={X(o.x0) + (o.wM * S) / 2} y1={oy} x2={X(o.x0) + (o.wM * S) / 2} y2={oy + o.hM * S} />
                  <line x1={X(o.x0)} y1={oy + (o.hM * S) / 2} x2={X(o.x0) + o.wM * S} y2={oy + (o.hM * S) / 2} />
                </g>
              )}
            </g>
          );
        })}

        {/* safety railings on veranda extents, every floor */}
        {g.rails.map((r, i) => {
          const yBase = g.plinthM + r.floor * g.floorHM;
          const yTopRail = Y(yBase + 1.0);
          const yFloor = Y(yBase);
          const x0 = X(Math.min(r.x0, r.x1)), x1 = X(Math.max(r.x0, r.x1));
          const nPost = Math.max(2, Math.round((x1 - x0) / (1.2 * S)));
          return (
            <g key={i} stroke={COL.rail}>
              <line x1={x0} y1={yTopRail} x2={x1} y2={yTopRail} strokeWidth={2} />
              {Array.from({ length: nPost + 1 }, (_, k) => {
                const px = x0 + ((x1 - x0) * k) / nPost;
                return <line key={k} x1={px} y1={yTopRail} x2={px} y2={yFloor} strokeWidth={0.8} />;
              })}
            </g>
          );
        })}

        {/* staircases */}
        {g.stairs.map((s, i) => {
          const x0 = X(s.x0), w = s.wM * S;
          if (!s.profile) {
            // end silhouette: block up to its rise + railing hint
            const hy = Y(s.riseM);
            return (
              <g key={i}>
                <rect x={x0} y={hy} width={w} height={groundY - hy} fill={COL.stairFill} stroke={COL.stair} strokeWidth={1.2} />
                <line x1={x0} y1={hy} x2={x0 + w} y2={hy} stroke={COL.stair} strokeWidth={1.6} />
                <text x={x0 + w / 2} y={groundY + 10} textAnchor="middle" fontSize={6.5} fill={COL.stair}>{s.label}</text>
              </g>
            );
          }
          // true stepped profile
          const flightW = Math.max(0.05, s.wM - s.landingM);
          const stepsPts: string[] = [];
          const dir = s.lowAtStart ? 1 : -1;
          const startX = s.lowAtStart ? s.x0 : s.x0 + s.wM;
          const landX = s.lowAtStart ? s.x0 + flightW : s.x0 - 0 + s.landingM; // landing at the high end
          let cx = startX, cy = 0;
          stepsPts.push(`${X(cx)},${Y(cy)}`);
          for (let k = 0; k < s.steps; k++) {
            cy += s.riserM * (s.riseM / Math.max(0.001, s.steps * s.riserM)); // normalized riser
            stepsPts.push(`${X(cx)},${Y(cy)}`);
            cx += dir * (flightW / s.steps);
            stepsPts.push(`${X(cx)},${Y(cy)}`);
          }
          // landing flat at the high end
          const landEnd = s.lowAtStart ? s.x0 + s.wM : s.x0;
          stepsPts.push(`${X(landEnd)},${Y(cy)}`);
          const poly = `${stepsPts.join(" ")} ${X(landEnd)},${Y(0)} ${X(startX)},${Y(0)}`;
          const railY0 = Y(1.0), railY1 = Y(cy + 1.0);
          return (
            <g key={i}>
              <polygon points={poly} fill={COL.stairFill} stroke={COL.stair} strokeWidth={1.2} />
              {s.handrail && (
                <line x1={X(startX)} y1={railY0} x2={X(landEnd)} y2={railY1} stroke={COL.rail} strokeWidth={1.6} />
              )}
              <text x={X(s.x0) + w / 2} y={groundY + 10} textAnchor="middle" fontSize={6.5} fill={COL.stair}>
                {s.label} · {s.steps} steps · R {Math.round(s.riserM * 1000)} mm
              </text>
            </g>
          );
        })}

        {/* ground line */}
        <line x1={-10} y1={groundY} x2={spanX * S + 10} y2={groundY} stroke={COL.wall} strokeWidth={2.4} />

        {/* dimensions: overall width below, heights at right */}
        <text x={(X(g.x0) + X(g.x1)) / 2} y={groundY + 22} textAnchor="middle" fontSize={10} fontWeight={700} fill={COL.overall}>
          ← {fmt(g.totalWidthM)} →
        </text>
        <g fontSize={8} fill={COL.dim}>
          <text x={X(g.bodyX1) + 6} y={(Y(g.plinthM) + Y(g.plinthM + g.bodyHM)) / 2}>{fmt(g.bodyHM)}</text>
          {g.plinthM > 0.01 && <text x={X(g.bodyX1) + 6} y={(Y(0) + Y(g.plinthM)) / 2 + 3}>plinth {fmt(g.plinthM)}</text>}
          {g.roof.type !== "flat" && <text x={X(g.bodyX1) + 6} y={(eaveY + ridgeY) / 2}>{fmt(g.roof.riseM)}</text>}
        </g>
      </g>
    </svg>
  );
}
