"use client";

import { forwardRef, useRef, useState } from "react";
import { Download, FileImage, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "@/hooks/use-toast";
import type {
  LabourColonyResult, RoomFloorPlanConfig, ElevationRoofConfig, ElevationStructureConfig,
} from "@/lib/quotation/labourColony";
import { buildElevation, resolveRoof, resolveStructure, type ElevationGeom, type ElevationFace } from "@/lib/quotation/elevation";
import { formatLen, type LengthUnit } from "@/lib/quotation/units";
import { downloadSvgFile, downloadSvgAsPdf } from "@/lib/pdf/svgExport";

/**
 * Four ELEVATIONS (Front / Rear / Left / Right) for the Labour Colony calculator.
 *
 * Every face is generated by buildElevation(), which derives its geometry from the SAME
 * buildRoomFloorPlan() output the 2D room-wise floor plan renders — so the elevations update
 * live with every calculator change (rooms, floors, sizes, doors/windows, verandas, railing,
 * staircases, units) and can never disagree with the plan.
 *
 * The SIDE (left/right) faces are gable ends: the plan puts every window on a top/bottom wall,
 * so a side elevation legitimately shows no openings. What makes it readable is the STRUCTURE —
 * the steel column grid, the cross ("X") bracing, the sandwich-panel courses, the open veranda
 * decks either side of the walled body, and the level marks. All of that is derived from the
 * plan + the project's own MemberSections, and all of it is customisable below.
 *
 * Roof, plinth and structural detailing are drawing-only settings — they never touch the BOQ.
 */

const COL = {
  wall: "#334155", body: "#f1f5f9", panel: "#e2e8f0", plinth: "#cbd5e1", roof: "#cbd5e1",
  roofEdge: "#64748b",
  steel: "#1d4ed8", steelDark: "#1e3a8a", brace: "#2563eb",   // "blue-painted steel frame"
  door: "#dc2626", doorFill: "#fee2e2", window: "#2563eb", windowFill: "#dbeafe",
  floor: "#94a3b8", rail: "#059669", stair: "#b45309", stairFill: "#fde68a",
  deck: "#fef9c3", deckEdge: "#a16207",
  dim: "#475569", overall: "#0369a1", ink: "#0f172a", note: "#64748b",
};

const FACES: { face: ElevationFace; title: string }[] = [
  { face: "front", title: "Front Elevation" },
  { face: "rear", title: "Rear Elevation" },
  { face: "left", title: "Left Side Elevation" },
  { face: "right", title: "Right Side Elevation" },
];

export function LabourColonyDrawings({ result, unit, floorPlan, onFloorPlanChange, plinthM, projectName }: {
  result: LabourColonyResult;
  unit: LengthUnit;
  floorPlan?: RoomFloorPlanConfig;
  onFloorPlanChange?: (fp: RoomFloorPlanConfig) => void;
  plinthM?: number;
  projectName?: string;
}) {
  const fmt = (m: number) => formatLen(m, unit);
  const roof = resolveRoof(floorPlan);
  const st = resolveStructure(floorPlan, result.sections);
  const editable = !!onFloorPlanChange;

  const setRoof = (patch: Partial<ElevationRoofConfig>) =>
    onFloorPlanChange?.({ ...(floorPlan ?? {}), roof: { ...(floorPlan?.roof ?? {}), ...patch } });
  const setStruct = (patch: Partial<ElevationStructureConfig>) =>
    onFloorPlanChange?.({ ...(floorPlan ?? {}), structure: { ...(floorPlan?.structure ?? {}), ...patch } });

  const selCls = "h-8 rounded-md border border-slate-300 bg-white px-2 text-sm text-slate-900 outline-none focus:border-amber-400 disabled:opacity-60";
  const numCls = "h-8 w-24 rounded-md border border-slate-300 bg-white px-2 text-sm text-slate-900 outline-none focus:border-amber-400 disabled:opacity-60";

  return (
    <div className="space-y-4">
      {/* ---------- roof (drawing-only) ---------- */}
      <div className="flex flex-wrap items-end gap-3 rounded-xl border bg-slate-50 p-3 text-xs">
        <div className="w-full text-[11px] font-semibold uppercase tracking-wide text-slate-500">Roof</div>
        <label className="font-medium text-slate-600">
          <span className="mb-1 block">Roof type</span>
          <select value={roof.type} onChange={(e) => setRoof({ type: e.target.value as ElevationRoofConfig["type"] })}
            className={selCls} disabled={!editable}>
            <option value="gable">Gable (ridge along length)</option>
            <option value="hip">Hip</option>
            <option value="mono">Mono slope</option>
            <option value="flat">Flat</option>
          </select>
        </label>
        {roof.type !== "flat" && (
          <label className="font-medium text-slate-600">
            <span className="mb-1 block">Roof rise (m)</span>
            <input type="number" step={0.1} min={0.2} value={roof.riseM}
              onChange={(e) => setRoof({ riseM: Math.max(0.2, parseFloat(e.target.value) || 0.7) })}
              onFocus={(e) => e.currentTarget.select()} disabled={!editable} className={numCls} />
          </label>
        )}
        <label className="font-medium text-slate-600">
          <span className="mb-1 block">Eave overhang (m)</span>
          <input type="number" step={0.05} min={0} value={roof.overhangM}
            onChange={(e) => setRoof({ overhangM: Math.max(0, parseFloat(e.target.value) || 0) })}
            onFocus={(e) => e.currentTarget.select()} disabled={!editable} className={numCls} />
        </label>
        <div className="ml-auto text-[11px] text-slate-500">
          Plinth {fmt(plinthM ?? 0.45)} (from Civil tab) · elevations derive from the room-wise floor plan — always in sync
        </div>
      </div>

      {/* ---------- structural frame (drawing-only) ---------- */}
      <div className="flex flex-wrap items-end gap-3 rounded-xl border border-blue-200 bg-blue-50/60 p-3 text-xs">
        <div className="w-full text-[11px] font-semibold uppercase tracking-wide text-blue-800">
          Structural frame — columns &amp; cross bracing
        </div>

        <label className="flex items-center gap-1.5 font-medium text-slate-700">
          <input type="checkbox" checked={st.columns} disabled={!editable}
            onChange={(e) => setStruct({ columns: e.target.checked })} />
          Steel column grid
        </label>

        <label className="font-medium text-slate-600">
          <span className="mb-1 block">Max column spacing (m)</span>
          <input type="number" step={0.25} min={0.6} value={st.maxBaySpacingM}
            onChange={(e) => setStruct({ maxBaySpacingM: Math.max(0.6, parseFloat(e.target.value) || 3) })}
            onFocus={(e) => e.currentTarget.select()} disabled={!editable} className={numCls} />
        </label>

        <label className="font-medium text-slate-600">
          <span className="mb-1 block">Column width (m)</span>
          <input type="number" step={0.01} min={0.05} max={0.6} value={st.columnWidthM}
            onChange={(e) => setStruct({ columnWidthM: Math.max(0.05, parseFloat(e.target.value) || 0.1) })}
            onFocus={(e) => e.currentTarget.select()} disabled={!editable} className={numCls} />
        </label>

        <label className="font-medium text-slate-600">
          <span className="mb-1 block">Cross bracing</span>
          <select value={st.bracePattern} onChange={(e) => setStruct({ bracePattern: e.target.value as "x" | "single" | "none" })}
            className={selCls} disabled={!editable}>
            <option value="x">Cross “X” bracing</option>
            <option value="single">Single diagonal</option>
            <option value="none">None</option>
          </select>
        </label>

        <label className="font-medium text-slate-600">
          <span className="mb-1 block">Braced bays</span>
          <select value={st.braceBays} onChange={(e) => setStruct({ braceBays: e.target.value as "all" | "ends" | "alternate" })}
            className={selCls} disabled={!editable || st.bracePattern === "none"}>
            <option value="all">All bays</option>
            <option value="ends">End bays only</option>
            <option value="alternate">Alternate bays</option>
          </select>
        </label>

        <label className="font-medium text-slate-600">
          <span className="mb-1 block">Braced floors</span>
          <select value={st.braceFloors} onChange={(e) => setStruct({ braceFloors: e.target.value as "all" | "ground" | "upper" })}
            className={selCls} disabled={!editable || st.bracePattern === "none"}>
            <option value="all">All floors</option>
            <option value="ground">Ground floor only</option>
            <option value="upper">Upper floors only</option>
          </select>
        </label>

        <label className="font-medium text-slate-600">
          <span className="mb-1 block">Brace thickness (m)</span>
          <input type="number" step={0.01} min={0.02} max={0.3} value={st.braceThickM}
            onChange={(e) => setStruct({ braceThickM: Math.max(0.02, parseFloat(e.target.value) || 0.05) })}
            onFocus={(e) => e.currentTarget.select()} disabled={!editable || st.bracePattern === "none"} className={numCls} />
        </label>

        <label className="font-medium text-slate-600">
          <span className="mb-1 block">Panel course (m)</span>
          <input type="number" step={0.1} min={0} value={st.panelCourseM}
            onChange={(e) => setStruct({ panelCourseM: Math.max(0, parseFloat(e.target.value) || 0) })}
            onFocus={(e) => e.currentTarget.select()} disabled={!editable} className={numCls} />
        </label>

        <label className="flex items-center gap-1.5 font-medium text-slate-700">
          <input type="checkbox" checked={st.braceClearOpenings} disabled={!editable || st.bracePattern === "none"}
            onChange={(e) => setStruct({ braceClearOpenings: e.target.checked })} />
          Keep bracing clear of openings
        </label>

        <label className="flex items-center gap-1.5 font-medium text-slate-700">
          <input type="checkbox" checked={st.showDecks} disabled={!editable}
            onChange={(e) => setStruct({ showDecks: e.target.checked })} />
          Veranda decks (side views)
        </label>

        <label className="flex items-center gap-1.5 font-medium text-slate-700">
          <input type="checkbox" checked={st.showDims} disabled={!editable}
            onChange={(e) => setStruct({ showDims: e.target.checked })} />
          Dimensions &amp; level marks
        </label>

        <div className="w-full text-[11px] text-slate-500">
          Column &amp; brace sizes default to this project’s steel — columns{" "}
          <b>{result.sections.columns.shape} {result.sections.columns.a}×{result.sections.columns.b}</b>, bracing{" "}
          <b>{result.sections.bracing.shape} {result.sections.bracing.a}×{result.sections.bracing.b}</b>. Column lines are
          placed at every room partition, wall face and veranda edge, then any bay wider than the max spacing is subdivided.
        </div>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
        {FACES.map(({ face, title }) => (
          <ElevationCard key={face} face={face} title={title} projectName={projectName}
            g={buildElevation(result, floorPlan, face, { plinthM })} fmt={fmt} />
        ))}
      </div>

      <div className="flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-slate-600">
        <span className="flex items-center gap-1"><span className="inline-block h-2.5 w-2.5 rounded-sm" style={{ background: COL.steel }} /> Steel column</span>
        <span className="flex items-center gap-1"><span className="inline-block h-0.5 w-4" style={{ background: COL.brace }} /> Cross bracing</span>
        <span className="flex items-center gap-1"><span className="inline-block h-2 w-4 border" style={{ background: COL.body, borderColor: COL.wall }} /> Sandwich panel wall</span>
        <span className="flex items-center gap-1"><span className="inline-block h-2 w-4 border" style={{ background: COL.windowFill, borderColor: COL.window }} /> Window</span>
        <span className="flex items-center gap-1"><span className="inline-block h-2 w-4 border" style={{ background: COL.doorFill, borderColor: COL.door }} /> Door</span>
        <span className="flex items-center gap-1"><span className="inline-block h-2 w-4 border" style={{ background: COL.deck, borderColor: COL.deckEdge }} /> Veranda / walkway</span>
        <span className="flex items-center gap-1"><span className="inline-block h-0.5 w-4" style={{ background: COL.rail }} /> Safety railing</span>
        <span className="flex items-center gap-1"><span className="inline-block h-2.5 w-2.5 rounded-sm border" style={{ background: COL.stairFill, borderColor: COL.stair }} /> Staircase</span>
        <span className="flex items-center gap-1"><span className="inline-block h-2.5 w-2.5 rounded-sm border" style={{ background: COL.plinth, borderColor: COL.wall }} /> Plinth</span>
        <span className="text-slate-400">Derived from the floor plan · schematic reference, not stamped CAD</span>
      </div>
    </div>
  );
}

/* ============================================================ elevation card */

function ElevationCard({ g, title, face, fmt, projectName }: {
  g: ElevationGeom; title: string; face: ElevationFace;
  fmt: (m: number) => string; projectName?: string;
}) {
  const svgRef = useRef<SVGSVGElement>(null);
  const [busy, setBusy] = useState(false);
  const slug = (projectName || "labour-colony").trim().replace(/[^\w]+/g, "-").replace(/^-|-$/g, "").toLowerCase();
  const base = `${slug}-${face}-elevation`;

  const download = async (kind: "svg" | "pdf") => {
    if (!svgRef.current) return;
    setBusy(true);
    try {
      if (kind === "svg") downloadSvgFile(svgRef.current, base);
      else await downloadSvgAsPdf(svgRef.current, base, `${title}${projectName ? ` — ${projectName}` : ""}`,
        `${fmt(g.totalWidthM)} wide × ${fmt(g.totalHM)} high · ${g.floors} floor${g.floors > 1 ? "s" : ""} · ${g.roof.type} roof`);
      toast({ title: `${title} downloaded` });
    } catch (err: unknown) {
      console.error("Elevation download failed:", err);
      const msg = err instanceof Error ? err.message : "";
      toast({
        title: "Could not download the elevation",
        description: msg ? msg.slice(0, 160) : "Please try again.",
        variant: "destructive",
      });
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="rounded-2xl border bg-white p-4">
      <div className="mb-2 flex items-start justify-between gap-2">
        <div>
          <div className="font-display font-bold text-sm text-slate-800">{title}</div>
          <div className="text-xs text-slate-500">
            {fmt(g.totalWidthM)} wide · {fmt(g.totalHM)} high · {g.floors} floor{g.floors > 1 ? "s" : ""} · roof: {g.roof.type}
            {g.braces.length > 0 && <> · {g.braces.length} braced panel{g.braces.length > 1 ? "s" : ""}</>}
          </div>
        </div>
        <div className="flex shrink-0 gap-1.5 print:hidden">
          <Button type="button" variant="outline" size="sm" className="gap-1.5" disabled={busy} onClick={() => download("svg")}>
            <FileImage className="h-4 w-4" /> SVG
          </Button>
          <Button type="button" size="sm" className="gap-1.5" disabled={busy} onClick={() => download("pdf")}>
            {busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />} Download
          </Button>
        </div>
      </div>
      <div className="overflow-x-auto">
        <ElevationSvg ref={svgRef} g={g} fmt={fmt} />
      </div>
    </div>
  );
}

/* ================================================================ SVG face */

const ElevationSvg = forwardRef<SVGSVGElement, { g: ElevationGeom; fmt: (m: number) => string }>(
  function ElevationSvg({ g, fmt }, ref) {
    const spanX = Math.max(1, g.x1 - g.x0);
    const S = Math.min(34, Math.max(9, 640 / spanX));   // px per metre
    const PAD_L = 78, PAD_R = 78, PAD_T = 30;
    const PAD_B = g.structure.showDims ? 74 : 34;

    const H = g.plinthM + g.bodyHM;                     // wall height above ground
    const Ytop = g.roof.riseM;                          // roof band above the walls
    const X = (m: number) => PAD_L + (m - g.x0) * S;
    const Y = (mFromGround: number) => PAD_T + (Ytop + H - mFromGround) * S;

    const svgW = spanX * S + PAD_L + PAD_R;
    const svgH = (Ytop + H) * S + PAD_T + PAD_B;

    const groundY = Y(0);
    const eaveY = Y(H);
    const ridgeY = Y(H + g.roof.riseM);
    const isSide = g.face === "left" || g.face === "right";

    const bodyPx = { x: X(g.bodyX0), w: (g.bodyX1 - g.bodyX0) * S };
    const deckPx = { x: X(g.deckX0), w: (g.deckX1 - g.deckX0) * S };
    const rx0 = X(g.roofX0), rx1 = X(g.roofX1);

    /* ---------------- roof ---------------- */
    let roofEl: React.ReactNode;
    if (g.roof.type === "flat") {
      const t = Math.max(3, 0.15 * S);
      roofEl = <rect x={rx0} y={eaveY - t} width={rx1 - rx0} height={t} fill={COL.roof} stroke={COL.roofEdge} strokeWidth={1.3} />;
    } else if (g.roof.type === "mono") {
      // A mono slope has ONE high side; the opposite face sees it fall the other way, so the apex
      // must mirror on the "rear"/"right" views or the two faces would contradict each other.
      const flipped = g.face === "rear" || g.face === "right";
      roofEl = (
        <polygon
          points={flipped
            ? `${rx0},${eaveY} ${rx1},${eaveY} ${rx0},${ridgeY}`
            : `${rx0},${eaveY} ${rx1},${eaveY} ${rx1},${ridgeY}`}
          fill={COL.roof} stroke={COL.roofEdge} strokeWidth={1.3} />
      );
    } else if (isSide) {
      // gable / hip seen from the END → the true sloped profile (hip is slightly truncated)
      const mid = (rx0 + rx1) / 2;
      roofEl = g.roof.type === "hip"
        ? <polygon points={`${rx0},${eaveY} ${mid - 0.08 * (rx1 - rx0)},${ridgeY} ${mid + 0.08 * (rx1 - rx0)},${ridgeY} ${rx1},${eaveY}`}
            fill={COL.roof} stroke={COL.roofEdge} strokeWidth={1.4} />
        : <polygon points={`${rx0},${eaveY} ${mid},${ridgeY} ${rx1},${eaveY}`} fill={COL.roof} stroke={COL.roofEdge} strokeWidth={1.4} />;
    } else {
      // long faces: gable shows the ridge band; hip shows a trapezoid
      roofEl = g.roof.type === "hip"
        ? <polygon points={`${rx0},${eaveY} ${rx0 + 0.15 * (rx1 - rx0)},${ridgeY} ${rx1 - 0.15 * (rx1 - rx0)},${ridgeY} ${rx1},${eaveY}`}
            fill={COL.roof} stroke={COL.roofEdge} strokeWidth={1.3} />
        : (
          <g>
            <rect x={rx0} y={ridgeY} width={rx1 - rx0} height={eaveY - ridgeY} fill={COL.roof} stroke={COL.roofEdge} strokeWidth={1.3} />
            <line x1={rx0} y1={ridgeY} x2={rx1} y2={ridgeY} stroke={COL.wall} strokeWidth={1.6} />
          </g>
        );
    }

    /* ---------------- level marks (left) ---------------- */
    const levels: { m: number; label: string }[] = [
      { m: 0, label: "GL" },
      { m: g.plinthM, label: "FFL" },
    ];
    for (let f = 1; f < g.floors; f++) levels.push({ m: g.plinthM + f * g.floorHM, label: f === 1 ? "FFL 1" : `FFL ${f}` });
    levels.push({ m: H, label: "EAVE" });
    // A flat roof still has a drawn slab whose rise is counted in totalHM — mark its top too, or
    // the level marks would stop below the highest drawn line and the heights would not add up.
    levels.push({ m: H + g.roof.riseM, label: g.roof.type === "flat" ? "ROOF" : "RIDGE" });

    return (
      <svg ref={ref} viewBox={`0 0 ${svgW} ${svgH}`} className="w-full h-auto" style={{ minWidth: Math.min(svgW, 660) }}>
        {roofEl}

        {/* ---- open veranda / walkway decks (side faces): slab edge + railing, NOT wall ---- */}
        {g.decks.map((d, i) => {
          const yF = g.plinthM + d.floor * g.floorHM;
          const slabT = Math.max(3, 0.16 * S);
          const dx0 = X(Math.min(d.x0, d.x1)), dx1 = X(Math.max(d.x0, d.x1));
          const railTop = Y(yF + 1.0), yFloor = Y(yF);
          const nPost = Math.max(2, Math.round((dx1 - dx0) / (0.9 * S)));
          return (
            <g key={`deck${i}`}>
              {/* the walkway is open — tint it so it never reads as solid wall */}
              <rect x={dx0} y={railTop} width={dx1 - dx0} height={yFloor - railTop} fill={COL.deck} fillOpacity={0.5} stroke="none" />
              <rect x={dx0} y={yFloor} width={dx1 - dx0} height={slabT} fill={COL.plinth} stroke={COL.deckEdge} strokeWidth={1.1} />
              {d.railing && (
                <g stroke={COL.rail}>
                  <line x1={dx0} y1={railTop} x2={dx1} y2={railTop} strokeWidth={2} />
                  <line x1={dx0} y1={railTop + (yFloor - railTop) * 0.5} x2={dx1} y2={railTop + (yFloor - railTop) * 0.5} strokeWidth={1} />
                  {Array.from({ length: nPost + 1 }, (_, k) => {
                    const px = dx0 + ((dx1 - dx0) * k) / nPost;
                    return <line key={k} x1={px} y1={railTop} x2={px} y2={yFloor} strokeWidth={0.8} />;
                  })}
                </g>
              )}
            </g>
          );
        })}

        {/* ---- WALLED BODY (solid sandwich-panel wall only — verandas excluded) ---- */}
        <rect x={bodyPx.x} y={Y(H)} width={bodyPx.w} height={g.bodyHM * S}
          fill={COL.body} stroke={COL.wall} strokeWidth={1.8} />

        {/* horizontal sandwich-panel courses */}
        {g.courses.map((y, i) => (
          <line key={`c${i}`} x1={bodyPx.x} y1={Y(y)} x2={bodyPx.x + bodyPx.w} y2={Y(y)}
            stroke={COL.panel} strokeWidth={1} />
        ))}

        {/* floor lines across the walled body */}
        {Array.from({ length: g.floors - 1 }, (_, f) => (
          <line key={`f${f}`} x1={bodyPx.x} y1={Y(g.plinthM + (f + 1) * g.floorHM)} x2={bodyPx.x + bodyPx.w}
            y2={Y(g.plinthM + (f + 1) * g.floorHM)} stroke={COL.floor} strokeWidth={1.3} />
        ))}

        {/* ---- CROSS BRACING (behind the columns, inside the panel bays) ---- */}
        {g.braces.map((b, i) => {
          const inset = (g.structure.columnWidthM / 2) * S;
          const bx0 = Math.min(X(b.x0), X(b.x1)) + inset;
          const bx1 = Math.max(X(b.x0), X(b.x1)) - inset;
          if (bx1 - bx0 < 3) return null;
          const yBot = Y(b.y0), yTop = Y(b.y1);
          const sw = Math.max(1.6, b.thickM * S);
          return (
            <g key={`b${i}`} stroke={COL.brace} strokeWidth={sw} strokeLinecap="round" opacity={0.9}>
              <line x1={bx0} y1={yBot} x2={bx1} y2={yTop} />
              {b.pattern === "x" && <line x1={bx0} y1={yTop} x2={bx1} y2={yBot} />}
            </g>
          );
        })}

        {/* ---- STEEL COLUMN GRID (bold, over the panels) ---- */}
        {g.columns.map((c, i) => {
          const w = Math.max(2.5, c.widthM * S);
          const cx = X(c.xM) - w / 2;
          return (
            <rect key={`col${i}`} x={cx} y={Y(H)} width={w} height={g.bodyHM * S}
              fill={COL.steel} stroke={COL.steelDark} strokeWidth={0.8} />
          );
        })}

        {/* ---- plinth band (full block width, incl. the verandas it carries) ---- */}
        <rect x={deckPx.x} y={Y(g.plinthM)} width={deckPx.w} height={g.plinthM * S}
          fill={COL.plinth} stroke={COL.wall} strokeWidth={1.2} />

        {/* ---- openings — true positions/sizes per floor ---- */}
        {g.openings.map((o, i) => {
          const yBase = g.plinthM + o.floor * g.floorHM;
          const oy = Y(yBase + o.sillM + o.hM);
          const ox = X(Math.min(o.x0, o.x0 + o.wM));
          const ow = Math.abs(o.wM) * S, ohh = o.hM * S;
          const isDoor = o.kind === "door";
          return (
            <g key={`o${i}`}>
              <rect x={ox} y={oy} width={ow} height={ohh}
                fill={isDoor ? COL.doorFill : COL.windowFill} stroke={isDoor ? COL.door : COL.window} strokeWidth={1.4} />
              {isDoor ? (
                <line x1={ox + ow * 0.82} y1={oy + ohh * 0.55} x2={ox + ow * 0.82} y2={oy + ohh * 0.65} stroke={COL.door} strokeWidth={1.6} strokeLinecap="round" />
              ) : (
                <g stroke={COL.window} strokeWidth={0.7}>
                  <line x1={ox + ow / 2} y1={oy} x2={ox + ow / 2} y2={oy + ohh} />
                  <line x1={ox} y1={oy + ohh / 2} x2={ox + ow} y2={oy + ohh / 2} />
                </g>
              )}
            </g>
          );
        })}

        {/* ---- safety railings on the veranda extents (front/rear faces) ---- */}
        {g.rails.map((r, i) => {
          const yBase = g.plinthM + r.floor * g.floorHM;
          const yTopRail = Y(yBase + 1.0), yFloor = Y(yBase);
          const x0 = X(Math.min(r.x0, r.x1)), x1 = X(Math.max(r.x0, r.x1));
          const nPost = Math.max(2, Math.round((x1 - x0) / (1.2 * S)));
          return (
            <g key={`r${i}`} stroke={COL.rail}>
              <line x1={x0} y1={yTopRail} x2={x1} y2={yTopRail} strokeWidth={2} />
              <line x1={x0} y1={yTopRail + (yFloor - yTopRail) * 0.5} x2={x1} y2={yTopRail + (yFloor - yTopRail) * 0.5} strokeWidth={0.9} />
              {Array.from({ length: nPost + 1 }, (_, k) => {
                const px = x0 + ((x1 - x0) * k) / nPost;
                return <line key={k} x1={px} y1={yTopRail} x2={px} y2={yFloor} strokeWidth={0.8} />;
              })}
            </g>
          );
        })}

        {/* ---- staircases ---- */}
        {g.stairs.map((s, i) => {
          const sx0 = X(Math.min(s.x0, s.x0 + s.wM)), w = Math.abs(s.wM) * S;
          if (!s.profile) {
            const hy = Y(s.riseM);
            return (
              <g key={`s${i}`}>
                <rect x={sx0} y={hy} width={w} height={groundY - hy} fill={COL.stairFill} stroke={COL.stair} strokeWidth={1.2} />
                <line x1={sx0} y1={hy} x2={sx0 + w} y2={hy} stroke={COL.stair} strokeWidth={1.6} />
                <text x={sx0 + w / 2} y={groundY + 11} textAnchor="middle" fontSize={6.5} fill={COL.stair}>{s.label}</text>
              </g>
            );
          }
          // true stepped profile — riser/going straight from the plan's staircase config
          const flightW = Math.max(0.05, s.wM - s.landingM);
          const dir = s.lowAtStart ? 1 : -1;
          const startX = s.lowAtStart ? s.x0 : s.x0 + s.wM;
          const stepRise = s.riseM / Math.max(1, s.steps);
          const pts: string[] = [];
          let cx = startX, cy = 0;
          pts.push(`${X(cx)},${Y(cy)}`);
          for (let k = 0; k < s.steps; k++) {
            cy += stepRise;
            pts.push(`${X(cx)},${Y(cy)}`);
            cx += dir * (flightW / s.steps);
            pts.push(`${X(cx)},${Y(cy)}`);
          }
          const landEnd = s.lowAtStart ? s.x0 + s.wM : s.x0;
          pts.push(`${X(landEnd)},${Y(cy)}`);
          const poly = `${pts.join(" ")} ${X(landEnd)},${Y(0)} ${X(startX)},${Y(0)}`;
          return (
            <g key={`s${i}`}>
              <polygon points={poly} fill={COL.stairFill} stroke={COL.stair} strokeWidth={1.2} />
              {s.handrail && (
                <>
                  <line x1={X(startX)} y1={Y(1.0)} x2={X(landEnd)} y2={Y(cy + 1.0)} stroke={COL.rail} strokeWidth={1.8} />
                  {Array.from({ length: 5 }, (_, k) => {
                    const t = (k + 0.5) / 5;
                    const px = X(startX + (landEnd - startX) * t);
                    const stepY = cy * t;
                    return <line key={k} x1={px} y1={Y(stepY)} x2={px} y2={Y(stepY + 1.0)} stroke={COL.rail} strokeWidth={0.8} />;
                  })}
                </>
              )}
              <text x={sx0 + w / 2} y={groundY + 11} textAnchor="middle" fontSize={6.5} fill={COL.stair}>
                {s.label} · {s.steps} steps · R {Math.round(s.riserM * 1000)} mm
              </text>
            </g>
          );
        })}

        {/* ---- ground line (hatched) ---- */}
        <line x1={X(g.x0) - 14} y1={groundY} x2={X(g.x1) + 14} y2={groundY} stroke={COL.ink} strokeWidth={2.6} />
        {Array.from({ length: 24 }, (_, k) => {
          const gx = X(g.x0) - 14 + ((X(g.x1) - X(g.x0) + 28) * k) / 23;
          return <line key={`h${k}`} x1={gx} y1={groundY} x2={gx - 5} y2={groundY + 5} stroke={COL.note} strokeWidth={0.7} />;
        })}

        {g.structure.showDims && (
          <>
            {/* ---- level marks (left): GL / FFL / EAVE / RIDGE with true heights ---- */}
            <g>
              {levels.map((lv, i) => {
                const ly = Y(lv.m);
                return (
                  <g key={`lv${i}`}>
                    <line x1={PAD_L - 60} y1={ly} x2={X(g.x0) - 2} y2={ly} stroke={COL.dim} strokeWidth={0.5} strokeDasharray="3 3" />
                    <polygon points={`${PAD_L - 60},${ly} ${PAD_L - 55},${ly - 3.4} ${PAD_L - 55},${ly + 3.4}`} fill={COL.dim} />
                    <text x={PAD_L - 53} y={ly - 2.4} fontSize={6.6} fontWeight={700} fill={COL.ink}>{lv.label}</text>
                    <text x={PAD_L - 53} y={ly + 6.4} fontSize={6.2} fill={COL.dim}>+{fmt(lv.m)}</text>
                  </g>
                );
              })}
            </g>

            {/* ---- bottom dimension chain: veranda | rooms | veranda (from the plan's own bands) ---- */}
            <g>
              {(() => {
                const dy = groundY + 26;
                return g.dimChain.map((b, i) => {
                  const a = X(b.x0), c = X(b.x0 + b.wM);
                  if (c - a < 8) return null;
                  return (
                    <g key={`dc${i}`}>
                      <line x1={a} y1={dy} x2={c} y2={dy} stroke={COL.dim} strokeWidth={0.9} />
                      <line x1={a} y1={dy - 4} x2={a} y2={dy + 4} stroke={COL.dim} strokeWidth={0.9} />
                      <line x1={c} y1={dy - 4} x2={c} y2={dy + 4} stroke={COL.dim} strokeWidth={0.9} />
                      <text x={(a + c) / 2} y={dy - 6} textAnchor="middle" fontSize={6.4} fill={COL.dim}>{fmt(b.wM)}</text>
                      <text x={(a + c) / 2} y={dy + 12} textAnchor="middle" fontSize={5.6} fill={COL.note}>
                        {b.kind === "veranda" ? "VERANDA" : b.kind === "stair" ? "STAIR" : b.kind === "gap" ? "GAP" : "ROOM"}
                      </text>
                    </g>
                  );
                });
              })()}
            </g>

            {/* ---- overall BUILDING width (excludes the roof overhang) ---- */}
            {(() => {
              const oy = groundY + 54, a = X(g.buildX0), c = X(g.buildX1);
              return (
                <g>
                  <line x1={a} y1={oy} x2={c} y2={oy} stroke={COL.overall} strokeWidth={1.1} />
                  <line x1={a} y1={oy - 5} x2={a} y2={oy + 5} stroke={COL.overall} strokeWidth={1.1} />
                  <line x1={c} y1={oy - 5} x2={c} y2={oy + 5} stroke={COL.overall} strokeWidth={1.1} />
                  <text x={(a + c) / 2} y={oy - 5} textAnchor="middle" fontSize={10} fontWeight={700} fill={COL.overall}>
                    ← {fmt(g.totalWidthM)} →
                  </text>
                </g>
              );
            })()}

            {/* ---- height dims (right) ---- */}
            <g fontSize={7.2} fill={COL.dim}>
              {(() => {
                const hx = X(g.x1) + 12;
                const rows: { y0: number; y1: number; label: string }[] = [];
                if (g.plinthM > 0.01) rows.push({ y0: 0, y1: g.plinthM, label: `plinth ${fmt(g.plinthM)}` });
                for (let f = 0; f < g.floors; f++) {
                  rows.push({ y0: g.plinthM + f * g.floorHM, y1: g.plinthM + (f + 1) * g.floorHM, label: fmt(g.floorHM) });
                }
                // include the flat-roof slab too — it is drawn and counted in totalHM, so omitting
                // it would leave the height dims not summing to the stated total
                rows.push({ y0: H, y1: H + g.roof.riseM, label: `roof ${fmt(g.roof.riseM)}` });
                return rows.map((r, i) => {
                  const ya = Y(r.y0), yb = Y(r.y1);
                  return (
                    <g key={`hd${i}`}>
                      <line x1={hx} y1={ya} x2={hx} y2={yb} stroke={COL.dim} strokeWidth={0.9} />
                      <line x1={hx - 4} y1={ya} x2={hx + 4} y2={ya} stroke={COL.dim} strokeWidth={0.9} />
                      <line x1={hx - 4} y1={yb} x2={hx + 4} y2={yb} stroke={COL.dim} strokeWidth={0.9} />
                      <text x={hx + 7} y={(ya + yb) / 2 + 2.4}>{r.label}</text>
                    </g>
                  );
                });
              })()}
              <text x={X(g.x1) + 12} y={ridgeY - 8} fontSize={7.4} fontWeight={700} fill={COL.overall}>
                total {fmt(g.totalHM)}
              </text>
            </g>
          </>
        )}
      </svg>
    );
  },
);
